#pragma once

enum BuffCategory
{
	BC_NORMAL,
	BC_ACCESOORY,
};

enum BuffType
{
	BT_NONE = 0,
	BT_DAMAGE_UPDOWN = 1,
	BT_SPEED_UPDOWN,
	BT_WOUNDED_UPDOWN,
	BT_RECOVERY,
	BT_RESTORATION,
	BT_FLYING_CONTRAL,
	BT_FLAME_STATUE,
	BT_FROZEN_STATUE,
	BT_STUN_STATUE,
	BT_TOXIC_STATUE,
	BT_PROTECTION,		// = 11
	BT_POTION,
	BT_PUSH_BACK,
	BT_REFLECT,
	BT_KING_SCALE,
	BT_RECOVERY_GAUGE,
	BT_RESTORATION_GAUGE,
	BT_CAMERA_BUFF,
	BT_CATCH_BUFF,
	BT_STEALTH,
	BT_STAT_ENHANCE,	// = 21
	BT_DURATION_SCALE,
	BT_HIDE,
	BT_WEAK_BOMB,
	BT_WEAK_MAGIC,
	BT_GAUGE_CLEAR,
	BT_FEAR,
	BT_DOUBLE_JUMP,
	BT_ABSOLUTE_PROTECTION,
	BT_CREEPING,
	BT_ELETRIC,			// = 31
	BT_MANA_SHIELD,
	BT_WARP,
	BT_CLOSEORDER,
	BT_STATE_PROTECTION,
	BT_FLOAT_BUFF,
	BT_JUMP_UPDOWN,
	BT_LANDING_RATE,
	BT_SCREEN_BLIND,
	BT_PUSH_BLOW_ENHANCE,
	BT_BREAK_FALL,		// = 41
	BT_BLOW_PUSH_POWER_BUFF,
	BT_HP_CONVERT,
	BT_STOP_MOTION,
	BT_DAMAGE_CONVERT,
	BT_SYSTEM_DAMAGE_RATE,
	BT_REVERSE_DIRECTION,
	BT_HP_STEAL,
	BT_HEAD_SCALE,
	BT_NOWOUND,
	BT_INVISIBLE,		// = 51
	BT_DISABLE_DASH,
	BT_CHANGE_MOTION,
	BT_GAUGE_STEAL,
	BT_RETURN_ATTACK,
	BT_FLOAT_MODE_EVENT_BUFF,
	BT_ACCUMULATE,
	BT_LIMIT_MOVE,
	BT_BUFF_FLY_JUMP,
	BT_DOWN_JUMPPING_BUFF,
	BT_DEFENSE_BREAK_BUFF,		// = 61
	BT_SELECT_COLLISION_BUFF,
	BT_RANGE_PROTECT_BUFF,
	BT_LIMIT_ACTION,
	BT_CURSE_BUFF,
	BT_DOWN_ROLLING_BUFF,
	BT_FRICTION_UP_DOWN,
	BT_FRONT_BACK_WOUND,
	BT_LAND_STUN,
	BT_AIR_ATTACK,
	BT_LAND_ROLLING_BUFF,			// = 71
	BT_NOT_MOVE_PROTECT,
	BT_ICE_BUFF,
	BT_DUMMY_BUFF,
	BT_SKIP_STUN,
	BT_WOUND_COLOR_CHANGE,
	BT_CHANGE_MOVE_SPEED,
	BT_STOP_PASSIVE,
	BT_ADD_SPECIAL_GAUGE,
	BT_REFUD_GAUGE,
	BT_PREVENT_DROP_ITEM,			// = 81
	BT_CHANGE_SKIN_COLOR,
	BT_ENABLE_WOUND_STUN_STATUE,
	BT_PULL_BUFF,
	BT_CHANGE_SOLDIER,
	BT_GHOST_STATE,
	BT_CALL_BY_STATE,
	BT_WITCH_FLY_STATE,
	BT_RANDOM_MOVE,
	BT_TELEPORT_ON_END_BUFF,
	BT_CHANGE_MESH,					// = 91
	BT_AUTO_FIRE,
	BT_DEFENSE_DAMAGE,
	BT_ADHESIVE_STATE,
	BT_SEAL_SKILL,
	BT_CALL_BUFF_ON_ATTACK,
	BT_MAGIC_STUN,
	BT_SPEED_ACCUMLATE,
	BT_CONTROL_WEAPON,
	BT_WALL_COLLISION,				// = 100
	BT_DEFENSE_DAMAGE2,
	BT_ACTIVE_COUNT,
	BT_INFECTION,
	BT_TARGET_EQUIP_OBJECTITEM,
	BT_CHANGE_TEAM,
	BT_SCREEN_BLIND2,
	BT_TRACE_MINE_STATE,
	BT_GAUGE_STEAL2,
	BT_RESTORATION_GAUGE2,
	BT_DISABLE_RECOVERY_SKILL_GAUGE,	// = 110
	BT_HIDE2,
	BT_HIT_COUNT_HOLD,
	BT_CREATE_WEAPON,
	BT_AFFECT_WOUNDED_VALUE,
	BT_EXTRA_CALL,
	BT_CALL_BY_NPC,
	BT_CREATE_DUMMY_CHAR,
	BT_GRAPPLING_PUSH,
	BT_MAGNETIC,
	BT_CREATE_DUMMY_CHAR2,				// = 120
	BT_WEAPON_ATTACH,
	BT_CREATE_DUMMY_CHAR3,
	BT_POSITION,						//버프생성자의 특정 위치로 케릭터를 옮긴다.
	BT_GARAVITY_UP_DOWN,
	BT_ESCAPE_DROP_ZONE,
	BT_PUSH_DIRECTION, 
	BT_WINDLORD,
	BT_CALL_RANDOM,
	BT_POSITION2,						//버프생성자의 특정 위치로 케릭터를 옮긴다.
	BT_CHECK_LIFE,						//생성자에서 특정 버프가 없을시 나도 죽는 버프	= 130
	BT_BUFF_MULTI_FLY_JUMP,
	BT_SPECIAL_GAUGE_RATE,
	BT_WIND_MAGNETIC,
	BT_DROP_ZONE,
	BT_DISPEL_BUFF,						// 사제 장신구를 비롯한 디스펠처리 개선하기 위한 버프
	BT_TRY_OUT_CHHECK,
	BT_CONCENTRATE_TARGET,
	BT_CREATE_DUMMY_CHAR4,
	BT_TARGET_CONTROL,
	BT_CREATE_BUFF,						// = 140
	BT_SKILL_GAUGE_CHECK,
	BT_REFLECT_DAMAGE,
	BT_ALPHA_RATE,
	BT_CONTROL_WEAPON2,
	BT_CALL_DESTROY,
	BT_CREATE_WEAPON_COUNT,
	BT_ROTATE_WEAPON,
	BT_WEAK_AIRBOMB,
	BT_DUMMY_ATTACH,
	BT_CREATE_DUMMY_CHAR5,				// = 150
	BT_LOOK_WEAPON,
	BT_BUFF_FLY_JUMP2,
	BT_TARGET_WEAPON,
	BT_LOOK_DUMMY,
	BT_CHECK_CHAIN,
	BT_STATE_PROTECTION_BY_PASSIVE,
	BT_POSITION3,
	BT_TARGET_MOVE,
	BT_SELF_CONTROL,
	BT_TARGET_DUMMY,					// = 160
	BT_ACTIVE_COUNT2,
	BT_CREATE_DUMMY_CHAR6,
	BT_AIR_BUFF,						//떨어 지지 않는다.
	BT_HIDE3,
	BT_WARP_FIND_DUMMY,
	BT_MARK_BUFF,
	BT_DUMMY_ATTACH2,
	BT_CHECK_LIFE2,
	BT_CREATE_OBJECT_ITEM,
	BT_DUMMY_ATTACH3,					// = 170
	BT_CHECK_JUMP,
	BT_HELICOPTER_ATTACH,
	BT_FLOAT2,
	BT_TARGET_WEAPON2,
	BT_HIDE4,
	BT_TARGET_RUSH_ATTACK,
	BT_THUNDER_BIRD_HOLD,
	BT_CHECK_STATE_END_ATTACK,
	BT_CHECK_STATE_END_CALL_BUFF,
	BT_MAP_EFFECT_BUFF,					// = 180
	BT_CREATE_DUMMY_BY_ATTACKED_BUFF,
	BT_MOVE_ATTACK,
	BT_DUMMY_CHAIN,
	BT_CREATE_DUMMY_CHAR7,
	BT_CHECK_CHAIN2,
	BT_PASSENGER_BUFF,
	BT_CREATE_DUMMY_CHAR8,
	BT_FLY_JUMP_EXTRA_ATTACK,
	BT_DUMMY_CHECK_BUFF,
	BT_CREATE_WEAPON_BUFF2,				// = 190
	BT_TARGET_MOVE_ATTACK,
	BT_WOUNDED_ADD_BUFF,
	BT_CREATE_WEAPON_BUFF3,
	BT_ATTACHED_DUMMY,
	BT_ATTACK_COUNT_BUFF,				//강림도령때 추가
	BT_CREATE_DUMMY_CHAR9,
	BT_HIT_COUNT_HOLD2,
	BT_CHECK_TARGET,
	BT_ATTACHED_CREATOR_CHAR,
	BT_NOVICE_GRADE_EFFECT,				// = 200
	BT_CALL_BUFF_ON_ATTACK2,
	BT_DEFENCE_CHANGE_BUFF,
	BT_COUNT_GATHER_ATTACK,
	BT_KEY_MARK_ATTACK,
	BT_BUFF_JUMP_ATTACK,
	BT_TRY_OUT_CHHECK2,
	BT_CALL_AND_DIE,
	BT_ACTIVE_COUNT3,
	BT_ATTACHED_DUMMY2,
	BT_TARGET_WEAPON3,					// = 210
	BT_SKILL_ATTACK_BUFF,
	BT_CREATE_AREA_WEAPON,
	BT_MOVE_ATTACK2,
	BT_WEAPON_FOLLOWED_OWNER,
	BT_TARGET_WEAPON4,
	BT_FLY_FOLLOW_STATE,
	BT_FLY_FOLLOW_STATE2,
	BT_MOVE_AREA_WEAPON,
	BT_ACC_SPEED_UPDOWN,
	BT_ACC_DAMAGE_UPDOWN,				// = 220
	BT_ACC_SYSTEM_DAMAGE_RATE,
	BT_ACC_ARMOR_CLASS_UP_DOWN_BUFF,
	BT_ACC_RESTORATION_GAUGE,
	BT_ACC_CRITICAL_RATE_BUFF,
	BT_ACC_CRITICAL_DAMAGE_RATE_BUFF,
	BT_ACC_ARMOR_PENTRATION_BUFF,
	BT_ACC_LANDING_RATE_BUFF,
	BT_ACC_CAMERA_BUFF,
	BT_ACC_GETUP_PROTECTION_DELAY_BUFF,
	BT_CREATE_WEAPON_BUFF4,				// = 230
	BT_CREATE_DUMMY_BY_ATTACKED_BUFF2,
	BT_TRAP_EYE_BUFF,
	BT_BUFF_AIR_WALK,
	BT_BLOW_PUSH_POWER_BUFF2,
	BT_WARP_BUFF,
	BT_CREATE_WEAPON_BUFF5,
	BT_WEAPON_IGNORE_BUFF,
	BT_WEAPON_REVERSE_IGNORE_BUFF,
	BT_KEY_TELEPORT_ATTACK,
	BT_TARGET_TELEPORT_ATTACK_BUFF,
	BT_JUMP_BOOST_BUFF,
	BT_STEAL_EQUIPMENT_BUFF,
	BT_ATTACK_KEY_ESCAPE_BUFF,
	BT_ATTACK_RANGE_CHECK_BUFF,
	BT_SUB_WEAPON_ATTACK_BUFF,
	BT_EXCEPT_GROWTH_BUFF,
	BT_RANGE_FEAR_BUFF,
	BT_MAGNETIC_FLYING_CONTRAL, // 마그네틱 버프 전용 2020-12-09
	MAX_BUFF_TYPE
};

struct CharBuffInfo
{
	ioHashString m_BuffName;
	ioHashString m_SkillName;
	DWORD m_GlobalTime;
	DWORD m_RemainTime;

	CharBuffInfo()
	{
		m_GlobalTime = 0;
		m_RemainTime = 0;
	}
};

typedef std::vector< CharBuffInfo > CharBuffInfoList;

enum BombType
{
	BET_NONE,
	BET_BOMB	= 1,
	BET_MINE	= 2,
	BET_AIRMINE = 3,
};

enum MagicType
{
	MET_NONE,
	MET_FIRE		= 1,
	MET_ICE			= 2,
	MET_LIGHTING	= 5,
};

enum CloseOrderWeaponType
{
	COWT_NONE,
	COWT_AREAWEAPON,
	COWT_WEAPON,
	COWT_BUFFSKILL_OWNER,
};

