#pragma once

//CLIENT SEND UCP PACKET
#define CUPK_CONNECT						0x4001
#define CUPK_SYNCTIME						0x4002
#define CUPK_CHAT							0x4003
#define CUPK_HOLE_CHECK                     0x4004
#define CUPK_RESERVE_ROOM_JOIN				0x4006  
#define CUPK_CHECK_KING_PING				0x4007
#define CUPK_CHECK_FLAG_PING				0x4009

#define CUPK_NEW_USER_INFO					0x4101
#define CUPK_EXIST_USER_INFO				0x4102
//#define CUPK_MODE_SPECIAL_INFO				0x4103

#define CUPK_CHAR_CONTROL					0x4104           // Index  
#define CUPK_ATTACK							0x4105           
#define CUPK_DEFENSE						0x4106
#define CUPK_DEFENSE_RELEASE				0x4107
#define CUPK_JUMP							0x4108			 
#define CUPK_JUMP_ATTACK					0x4109
#define CUPK_DASH_ATTACK					0x4110
#define CUPK_PICK_ITEM_TRY					0x4111

#define CUPK_USE_SKILL						0x4112			 // Index  
#define CUPK_WEAPON_DEFENSE					0x4113			 // Index  
#define CUPK_WEAPON_WOUNDED					0x4114 		     // Index  
#define CUPK_EXTEND_DEFENSE					0x4115
#define CUPK_DROP_DIE_MOTION				0x4116
#define CUPK_BLOW_GET_UP					0x4117
#define CUPK_DROP_DOWN_GET_UP				0x4118
#define CUPK_SKILL_END						0x4119
#define CUPK_SYSTEM_DAMAGE					0x4120
#define CUPK_MINE_WAIT_EXPLOSION			0x4121
#define CUPK_MINE_EXPLOSION					0x4122
#define CUPK_COUNTER_ATTACK					0x4123
#define CUPK_SYMBOL_DAMAMGED				0x4124
#define CUPK_EXPLOSION_ON_HAND				0x4125
#define CUPK_EXPLOSION_DROP					0x4126

#define CUPK_ITEM_GAUGE_OK					0x4127
#define CUPK_ITEM_GAUGE_CANCEL				0x4128
#define CUPK_FALL_DAMAGE					0x4129
#define CUPK_REQUEST_CHAR_CONTROL			0x4130
#define CUPK_ADD_NEW_BUFF					0x4131
#define CUPK_CHANGE_DASH_RUN				0x4132

#define CUPK_UPDATE_MAGIC_CIRCLE			0x4133

#define CUPK_FLY_JUMP						0x4135
#define CUPK_PRE_DEFENSE_RELEASE			0x4136
#define CUPK_DOUBLE_JUMP					0x4137
#define CUPK_VOICE_DATA                     0x4138
#define CUPK_SKILL_EXTRA_INFO				0x4139
#define CUPK_AUTO_SKILL                     0x4140
#define CUPK_PUSHSTRUCT_MOVE				0x4141
#define CUPK_PUSHSTRUCT_DAMAGE				0x4142
#define CUPK_PUSHSTRUCT_DELAY				0x4143
#define CUPK_PUSHSTRUCT_INFO				0x4144
#define CUPK_BUFF_JUMP						0x4145
#define CUPK_EXTEND_JUMP					0x4146
#define CUPK_RELEASE_FROZEN					0x4147
#define CUPK_AIM_FIRE						0x4148
#define CUPK_JUMPPING						0x4149
#define CUPK_FIELDITEM_INFO					0x4150
#define CUPK_DRINK							0x4151
#define CUPK_DROP_THROWBOMB					0x4152
#define CUPK_FALL_STATE						0x4153
#define CUPK_END_BUFF						0x4154
#define CUPK_P2P_PING                       0x4156
#define CUPK_SHOPPING                       0x4157
#define CUPK_END_AREA		                0x4158
#define CUPK_REMOVE_BUFF					0x4159
#define CUPK_PUSHSTRUCT_CREATEWEAPON		0x4160
#define CUPK_ELEVATOR_CHANGED				0x4161
#define CUPK_CLOSEORDER_DIRECTION			0x4162
#define CUPK_JUMP_DASH						0x4163
#define CUPK_BREAK_FALL						0x4164
#define CUPK_GUILD_INFO_CHANGE              0x4165
#define CUPK_EMOTICON_SYNC					0x4166
#define CUPK_USE_ITEM						0x4167
#define CUPK_RELEASE_FLOAT					0x4168
#define CUPK_RELEASE_CLOSEORDER				0x4169
#define CUPK_TELEPORT_STATE					0x4170
#define CUPK_CUSTOM_SOUND_INFO              0x4171
#define CUPK_CUSTOM_SOUND_DATA              0x4172
#define CUPK_CHANGE_CHARINFO                0x4173
#define CUPK_NONE_PLAY_STATE                0x4174
#define CUPK_SPECIAL_MOTION					0x4175
#define CUPK_USER_INFO_REFRESH              0x4176
#define CUPK_USER_INFO_SYNC                 0x4177
#define CUPK_EXTRAITEM_CHANGE               0x4178
#define CUPK_NPC_STUCK_STATE                0x4179
#define CUPK_PUSHSTRUCT_SEARCH_STATE		0x4180
#define CUPK_PUSHSTRUCT_TRACING_STATE		0x4181
#define CUPK_PUSHSTRUCT_FIRE_STATE			0x4182
#define CUPK_MONSTERCOIN_FIRST_SYNC         0x4183
#define CUPK_MONSTERCOIN_SYNC               0x4184
#define CUPK_RETURN_ATTACK_EXPLICIT			0x4185
#define CUPK_CHAIN_COLLISION				0x4186
#define CUPK_CHAIN_CHANGE					0x4187
#define CUPK_MONSTER_GLOBAL_TARGET          0x4188
#define CUPK_DUMMY_EXPLICIT					0x4189
#define CUPK_BUFF_FLY_JUMP					0x4190
#define CUPK_JUMP_AUTO_SHOT					0x4191
#define CUPK_EXCAVATING                     0x4192
#define CUPK_FIRST_SYNC_CHARINFO		    0x4193
#define CUPK_SYNC_CHARINFO                  0x4194
#define CUPK_DODGE_DEFENSE					0x4195
#define CUPK_TRACE_WEAPON					0x4196
#define CUPK_BALL_INFO						0x4197
#define CUPK_BALL_WEAPON_COL				0x4198
#define CUPK_BALL_WEAPON_CHANGE				0x4199
#define CUPK_TRACE_WEAPON_WAIT				0x4200
#define CUPK_AREAWEAPON						0x4201
#define CUPK_CURSE_ROLLING					0x4202
#define CUPK_DOWN_ROLLING					0x4203
#define CUPK_BUFF_AIR_ATTACK				0x4204
#define CUPK_NORMAL_DEAD_MINE				0x4205
#define CUPK_ETCITEM_MOTION                 0x4206
#define CUPK_PUSHSTRUCT_BOMBER				0x4207
#define CUPK_WEAPON_ATTACK_EXPLICIT			0x4208
#define CUPK_WEAPON_ATTACK_EXPLICIT_LIST	0x4209

#define CUPK_COLLECT_JUMP_ATTACK			0x4210
#define CUPK_NEW_JUMP_ATTACK				0x4211
#define CUPK_THROWBOMB_BOUND				0x4212
#define CUPK_DEFENSE_ATTACK					0x4213
#define CUPK_CREATE_STRUCT_STATE			0x4214

#define CUPK_WEAPON_SYNC					0x4216
#define CUPK_EXTEND_DASH					0x4217

#define CUPK_ETCITEM_MOTION_OPTION_FIRST_SYNC     0x4218
#define CUPK_ETCITEM_MOTION_OPTION_SYNC			  0x4219 

#define CUPK_GRAPPLING_SYNC					0x4220
#define CUPK_DUMMY_CHAR_SYNC				0x4221
#define CUPK_CHANGE_CHAR					0x4222
#define CUPK_JUMP_RELOAD					0x4223
#define CUPK_CROSS_BOW_JUMP					0x4224
#define CUPK_CROSS_BOW_JUMP_AIM				0x4225
#define CUPK_CROSS_BOW_AIM					0x4226
#define CUPK_BLOW_DASH						0x4227

#define CUPK_PICK_REWARD_ITEM_TRY			0x4228
#define CUPK_WEREWOLF_STATE					0x4229

#define CUPK_CHAR_ACTION_INFO				0x4230

#define CUPK_PASSIVE_GAUGE					0x4232
#define CUPK_WITCH_STATE					0x4233

#define CUPK_MACHINESTRUCT					0x4234

#define CUPK_DROP_SMARTBOOM					0x4235
#define CUPK_SMARTBOMB_BOUND				0x4236

#define CUPK_SUMMON_POS_SYNC				0x4237
#define CUPK_TRACE_MINE_WAIT_EXPLOSION		0x4238
#define CUPK_TRACE_MINE_NORMAL_DEAD			0x4239
#define CUPK_TRACE_MINE_FLY_TRACE			0x4240
#define CUPK_TRACE_MINE_EXPLOSION			0x4241

#define CUPK_COUNTER_ATTACK_SYNC			0x4242
#define CUPK_POWEREDARMOR_WOUNDED			0x4243

#define CUPK_GP_STATE						0x4244

#define CUPK_APPLY_EXTRA_BUFF_INFO			0x4245

#define CUPK_CHECK_ESCAPE_SKILL				0x4246

#define CUPK_SMART_BOOM_GENERATE_WEAPON		0x4247
#define CUPK_BUFF_MULTI_FLY					0x4248

#define CUPK_TRACE2_MINE_DELAY				0x4249
#define CUPK_TRACE2_MINE_NORMAL_DEAD		0x4250
#define CUPK_TRACE2_MINE_WAIT_EXPLOSION	0x4251
#define CUPK_TRACE2_MINE_EXPLOSION			0x4252

#define CUPK_REFLECT_ATTACK_EXPLICIT		0x4253

#define CUPK_AIR_MINE_WAIT_EXPLOSION		0x4254
#define CUPK_AIR_MINE_EXPLOSION				0x4255
#define CUPK_AIR_MINE_NORMAL_DEAD			0x4256
#define CUPK_EQUIP_SKILL_EXTRA_INFO			0x4257
#define CUPK_PET_SYNC						0x4258
#define CUPK_NAKORURU_STATE					0x4259
#define CUPK_LAG_ACTION		                0x4260
#define CUPK_INITIALIZE_SPECIAL_STATE       0x4261
#define CUPK_SPECIAL_STATE_SYNC	            0x4262
#define CUPK_RANDOM_APPLY_BUFF	            0x4263

#define CUPK_PASSIVE_SKILL_EXTRA_INFO		0x4264
#define CUPK_DELETE_ITEM_TRY				0x4265

// [배틀모드] 스킬 게이지 공유
#define CUPK_SYNC_SKILL_GAUGE               0x4266

#define CUPK_PREVENT_TARGET_BUFF			0X4267

// 닥터 스파이더가 사용하는 부스트 점프
#define CUPK_BOOST_JUMP						0X4268

// 로켓 런처 특별 상태 조준 구체 더미 자체는 다른 클라에게 보여주지 않기 위해 동기화 되지 않아 웨폰index 동기화를 따로 해줘야함
#define CUPK_HIDE_OBJECT_WEAPON_INDEX_SYNC	0X4269

//SERVER SEND UCP PACKET
#define SUPK_CONNECT                        0x6001
#define SUPK_SYNCTIME                       0x6002 
#define SUPK_MODE_PING			            0x6003
#define SUPK_CAMP_INFLUENCE_ALARM			0x6004
#define SUPK_SERVER_ALARM_MENT   			0x6005
#define SUPK_PROTECT                        0x6006
#define SUPK_WHOLE_CHAT                     0x6007

//LOG SERVER UDP PACKET           
#define LUPK_LOG                            0x9000

//SUPK_CAMP_INFLUENCE_ALARM
#define CAMP_INFLUENCE_ALARM          1
#define CAMP_TODAY_INFLUENCE_ALARM    2

//CUPK_EMOTICON_SYNC
enum EmoticionSync
{
	EMOTICON_HOME_PAGE				= 1,
	EMOTICON_SCREEN_SHOT			= 2,
	EMOTICON_PROTECT_WOUND			= 3,
	EMOTICON_COIN_EVENT				= 4,
	EMOTICON_NETWORK_BAD			= 5,
	EMOTICON_FISHING_GRADE			= 6,
	EMOTICON_NO_INPUT				= 7,
};


//CUPK_SYSTEM_DAMAGE
#define SYSTEM_DROP_DAMAGE		1
#define SYSTEM_FIRE_DAMAGE		2

//CUPK_CUSTOM_SOUND_INFO
#define HAVE_CUSTOM_SOUND  1
#define DONT_HAVE_CUSTOM_SOUND   2

//CUPK_BALL_INFO
#define BALL_INFO	1
#define BALL_KICK	2

//CUPK_FLY_JUMP
#define FLY_BOOST		1
#define FLY_CHANGE_DIR	2
#define FLY_HEIGHT_OFF	3

//CUPK_BOOST_JUMP
#define JUMP_BOOST				1
#define JUMP_BOOST_CHANGE_DIR	2

//CUPK_CREATE_STRUCT_STATE
#define CREATE_STRUCT_STATE	1
#define CREATE_STRUCT_SET	2

//CUPK_GRAPPLING_SYNC
#define GRAPPLING_ATTACKER		1
#define GRAPPLING_WOUNDED		2
#define GRAPPLING_PUSHED		3
#define GRAPPLING_WOUNDED_SKILL	4
#define GRAPPLING_WOUNDED_SWING	5
#define GRAPPLING_PSYC			6
#define GRAPPLING_PSYC_ACTION	7
#define GRAPPLING_JUMP_ATTACK	8
#define GRAPPLING_JUMP_WOUND	9
#define GRAPPLING_WOUNDED_ITEM	10
#define GRAPPLING_PUSHED_BUFF	11

//CUPK_JUMP_RELOAD
#define JUMP_RELOAD_SET		1
#define JUMP_RELOAD_SYNC	2

//CUPK_WEREWOLF_STATE
#define WEREWOLF_SET			1
#define WEREWOLF_RELEASE		2
#define WEREWOLF_ENABLE_GAUGE	3
#define WEREWOLF_RIDING_SET		4
#define BUBBLE_RIDING_SET		5
#define CHANGE_ON_SET			6
#define DR_SPIDER_SET			7
#define DR_SPIDER_ENABLE_GAUGE	8
#define DR_SPIDER_RIDING_SET	9

//CUPK_AREAWEAPON
#define AREAWEAPON_MOVE_INFO	1
#define AREAWEAPON_RANDOM_INFO	2
#define AREAWEAPON_SUB_INFO		3

//CUPK_WITCH_STATE
#define	WITCH_ENABLE_GAUGE	1

//CUPK_MACHINESTRUCT
#define MACHINE_TAKE_U		1
#define MACHINE_RELEASE_U	2
#define MACHINE_DIR_U		3
#define MACHINE_STATE_U		4

//CUPK_CHAR_ACTION_INFO
#define CHAR_ACTION_SYLPHID		1
#define CHAR_ACTION_DUMMY		2
#define CHAR_ACTION_GRAFFITI	3
#define CHAR_WEREWOLF_SYLPHID	4

//CUPK_GP_STATE
#define GP_STATE_SET		1
#define GP_STATE_RELEASE	2


//SUPK_SERVER_ALARM_MENT
#define UDP_SERVER_ALARM_EVENT						1
#define UDP_SERVER_ALARM_FISHING					2
#define UDP_SERVER_ALARM_FISHING_SELL				3
#define UDP_SERVER_ALARM_GRADE_UP					4
#define UDP_SERVER_ALARM_LEVEL_UP					5
#define UDP_SERVER_ALARM_GOLD_ITEM_EVENT			6
#define UDP_SERVER_ALARM_AWARD_LUCKY_PRESENT		7
#define UDP_SERVER_ALARM_LOSA_SEARCH_EVENT			8
#define UDP_SERVER_ALARM_COMPOUND_SUCCESS			9
#define UDP_SERVER_ALARM_MONSTER_SURVIVAL_CLEAR		10
#define UDP_SERVER_ALARM_RANDOM_DECO_PRESENT		11
#define UDP_SERVER_ALARM_EXTRAITEM					12
#define UDP_SERVER_ALARM_MODE_BONUS					13 
#define UDP_SERVER_ALARM_EXCAVATION					14
#define UDP_SERVER_ALARM_QUEST_COMPLETE				15
#define UDP_SERVER_ALARM_TRAD_ENABLE				16
#define UDP_SERVER_ALARM_GROWTH_CATALYST_SUCCESS	70
#define UDP_SERVER_ALARM_SUPERGASHAPON_PRESENT		371
#define UDP_SERVER_ALARM_ITEM_RECHARGE_SUCCESS		372
#define UDP_SERVER_ALARM_NEW_SUPERGASHAPON_PRESENT	373
#define UDP_SERVER_ALARM_COMPOUND_EXTRA_SUCCESS		573
#define UDP_SERVER_ALARM_COMPOUND_EXTRA_FAIL		574
#define UDP_SERVER_ALARM_COSTUME					875
#define UDP_SERVER_ALARM_OAK_PRESENT				1476
#define UDP_SERVER_ALARM_OAK_RESULT					1477
#define UDP_SERVER_ALARM_TIMEGATE_RESULT			1478
#define UDP_SERVER_ALARM_ETC_ITEM					1479

// SUPK_PROTECT
#define PROTECT_FAIL_NPROTECT_CHECK					1

