#pragma once


enum StatAttributeID
{
	//STR Stat
	SA_STR_DAMAGE_UP,
	SA_STR_PUSH_AMT_UP,
	SA_STR_BLOW_AMT_UP,
	SA_STR_FORCE_AMT_UP,
	SA_STR_WEIGHT_DOWN,
	SA_STR_GAUGE_FILL_UP,
	
	//DEX Stat
	SA_DEX_DAMAGE_UP,
	SA_DEX_FASTGETUP_SPEED_UP,
	SA_DEX_MOVE_SPEED_UP,
	SA_DEX_DASH_COOLTIME_DOWN,
	SA_DEX_GAUGE_FILL_UP,

	//INT Stat
	SA_INT_DAMAGE_UP,
	SA_INT_SKILL_READYTIME_DOWN,
	SA_INT_ABNORMAL_TIME_DOWN,
	SA_INT_INT_DAMAGE_DOWN,
	SA_INT_GAUGE_FILL_UP,

	//VIT Stat
	SA_VIT_MAX_HP_UP,
	SA_VIT_AC_UP,
	SA_VIT_FALL_DAMAGE_DOWN,
	SA_VIT_SCAIL_UP,
	SA_VIT_GAUGE_FILL_UP
};

