#pragma once

#define HIRE_LEADER_RIGHT_CODE	1
#define TIME_GATE_RIGHT_CODE	2
#define ITEM_N_SHOP_RIGHT_CODE	3
#define TRAING_RIGHT_CODE		4
#define COMMUNITY_RIGHT_CODE	5

#define HIRE_TROOPS1_RIGHT_CODE 20
#define HIRE_TROOPS2_RIGHT_CODE 21

