

#ifndef _ioFileTokenDefine_h_
#define _ioFileTokenDefine_h_

#define SKELETON_TOKEN	"SKL\0"
#define MATERIAL_TOKEN	"MTL\0"
#define ANIMATION_TOKEN	"ANI\0"
#define MESH_TOKEN		"MSH\0"
#define FONT_TOKEN		"FNT\0"
#define COL_MESH_TOKEN	"CMS\0"
#define PGF_TOKEN		"PGF\0"
#define ANIMATE_EFFECT_TOKEN "AFX\0"
#define OUTLINE_EDGE_TOKEN	"EDG\0"

#define SKELETON_VERSION	1000

#define MESH_VERSION		2000
#define VERTEX_COLOR_MESH_VERSION	2001
#define MESH_CONTROL_POINT_VERSION	2002

#define MATERIAL_VERSION		3000

#define ANIMATION_VER_DEFAULT	4000
#define ANIMATION_VER_COMP4		4001
#define ANIMATION_VER_COMP8		4002

#define FONT_VERSION		5000
#define COL_MESH_VERSION	5000
#define ANIMATE_EFFECT_VERSION 6000
#define OUTLINE_EDGE_VERSION 7000

#endif