// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#if !defined(AFX_STDAFX_H__0F866CD0_92C9_4EBB_ABC3_F76DD29BE1C0__INCLUDED_)
#define AFX_STDAFX_H__0F866CD0_92C9_4EBB_ABC3_F76DD29BE1C0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


// Insert your headers here
#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers


// TODO: reference additional headers your program requires here

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning(disable:4786)

// disable: "conversion from 'double' to 'float', possible loss of data
#   pragma warning(disable:4244)

// disable: "truncation from 'double' to 'float'
#   pragma warning(disable:4305)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#   pragma warning(disable:4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#   pragma warning(disable:4275)

// disable: "C++ Exception Specification ignored"
// This is because MSVC 6 did not implement all the C++ exception 
// specifications in the ANSI C++ draft.
#   pragma warning(disable:4290)

// disable: "no suitable definition provided for explicit template 
// instantiation request" Occurs in VC7 for no justifiable reason on all 
// #includes of Singleton
#   pragma warning(disable:4661)

#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <cstdarg>
#include <cmath>

// STL containers
#include <vector>
#include <map>
#include <string>
#include <set>
#include <list>
#include <deque>

// STL algorithms & functions
#include <algorithm>
#include <functional>
#include <utility>
#include <limits>

// C++ Stream stuff
#include <fstream>
#include <iostream>
#include <iomanip>
#include <sstream>

// Windows 
#include <windows.h>

#include "../LSLog/include/LSLog.h"

#ifdef _DEBUG
	#pragma comment(lib, "../LSLog/bin/LSLogd.lib" )
	#pragma comment(lib, "FreeType/Lib/freetype2312.lib")
#else
	#pragma comment(lib, "../LSLog/bin/LSLog.lib" )
	#pragma comment(lib, "FreeType/Lib/freetype2312_D.lib")
#endif

#ifndef FREETYPE_API
	#define FREETYPE_API __declspec(dllexport)
#endif

#include <ft2build.h>
#include FT_FREETYPE_H

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STDAFX_H__0F866CD0_92C9_4EBB_ABC3_F76DD29BE1C0__INCLUDED_)
