[NETWORK]
CSPORT = 20000
SSPORT = 20001
MSPORT = 7139

DBIP   = 172.20.20.110
DBPORT = 30911

;DBIP   = 172.20.20.110
;DBPORT = 30000

LOGDBIP        = 172.20.20.73
LOGDBSTARTPORT = 30001
LOGDBMaxPortCnt= 1

LOGSERVERIP   = 172.20.20.75
LOGSERVERPORT = 14009


MainServerIP   = 172.20.20.110
MainServerPORT = 40000

BillingRelayServerIP   = 172.20.20.75
; MY
;BillingRelayServerIP   = 172.20.20.59
BillingRelayServerStartPort = 14010
BillingRelayServerMaxPortCnt= 1

;60분마다 DB에 판매량 Select
[ClassPrice]
LoadTime = 60

[MemoryPool]
server_pool = 10

battleroom_pool  = 1000
ladderteam_pool  = 3000
room_pool	 = 1000
channel_pool	 = 5000
user_pool        = 1000
limit_user       = 1000

[SECURITY]
ON = 1
ONE_SEC_RCV = 1000

[FEATURE]
NAME=아마1 존
ARRAY = 1
MainSleepMS = 1
;DefaultiniLoad = 0

[HACK]
check_min_time = 7000
check_max_time = 12000
check_less_count = 1
check_over_count = 0
check_less_over_count = 0
check_total_count = 0

[SpeedHackQuiz]
max_answer_chance = 3
client_answer_time = 15000
server_answer_time = 16000

first_max_operand_size = 2
second_max_operand_size = 2
max_operator_type = 1

[AbuseQuiz]
max_answer_chance = 3
client_answer_time = 30000
server_answer_time = 31000

first_max_operand_size = 2
second_max_operand_size = 1
max_operator_type = 1

[AddExerciseCharIndex]
; 연습용병 index는 4284967295 ~ 4294967294 까지 천만개를 사용.
; 지금 서버에서는 4284967295 + start_add_exercise_char_index 부터 4284967295 + end_add_exercise_char_index 까지 사용
; limit_user 숫자만큼 할당 
max_index = 1000

[Xtrap]
; Xtrap 서버 기능 사용 유무 0 미사용 , 1사용
use = 0

[Local]
; 119483910 : 한국버전
Version = 119483910


; INFINITE 1일경우 Max 갯수 = INFI_Max값으로..
[SendBuffer Count]
;Min = 1
;Max = 10
Min = 10
Max = 1000


; Nagle Time은 10 ~ 30 ms로 설정. 유저가 렉으로 판단하지 않을정도의 적당한 수치를 찾아서..
; 레퍼런스 카운트 역시 SendBuffer가 너무 많이 쌓이지 않게 적당한 수치로 설정. 
[Nagle]
Nagle_Time = 100
Nagle_RefCnt = 55