//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AutoUpgrade.rc
//
#define IDD_AUTOUPGRADE_DIALOG          102
#define IDD_IOERRORDLG                  103
#define IDB_SOLUTIONBTN_SEA             104
#define IDR_MAINFRAME                   140
#define IDB_BACK                        142
#define IDB_HOVERBUTTON                 143
#define IDB_XBTN                        143
#define IDB_PROGRESSBAR                 144
#define IDB_TEXTBACK                    145
#define IDB_OPTIMIZE_BTN                146
#define IDB_BACK_US                     147
#define IDB_OPTIMIZE_BTN_US             148
#define IDD_DAUM_DLG                    149
#define IDB_START                       150
#define IDB_PROGRESSBAR_BACK            152
#define IDB_ERROR_BACK                  153
#define IDB_SOLUTIONBTN                 154
#define IDB_EXITBTN                     155
#define IDB_BITMAP1                     156
#define IDB_ERROR_XBTN                  156
#define IDB_ERROR_BACK_TW               157
#define IDB_BACK_TW                     158
#define IDB_EXITBTN_TW                  159
#define IDB_OPTIMIZE_BTN_TW             160
#define IDB_SOLUTIONBTN_TW              161
#define IDB_BITMAP3                     162
#define IDB_START_TW                    162
#define IDB_ERROR_BACK_US               164
#define IDB_EXITBTN_US                  165
#define IDB_BITMAP2                     166
#define IDB_START_US                    166
#define IDD_LOGINDLG                    168
#define IDB_LOGIN                       170
#define IDB_LOGIN_ENTER_BTN             171
#define IDB_LOGIN_ENTRY_BTN             172
#define IDB_LOGIN_FINDID_BTN            173
#define IDB_LOGIN_FINDPW_BTN            174
#define IDB_LOGIN_IDSAVE_BTN            175
#define IDB_LOGIN_X_BTN                 176
#define IDB_BACK_ID                     177
#define IDB_LOGIN_EDIT_SELECT           179
#define IDB_LOGIN_EDIT_NORMAL           181
#define IDB_LOGIN_EDIT_PW_NORMAL        182
#define IDB_LOGIN_EDIT_PW_SELECT        184
#define IDB_ERROR_BACK_ID               185
#define IDB_EXITBTN_ID                  186
#define IDB_OPTIMIZE_BTN_ID             187
#define IDB_SOLUTIONBTN_ID              188
#define IDB_BITMAP4                     189
#define IDB_START_ID                    189
#define IDB_ERROR_BACK_JP               190
#define IDB_BACK_JP                     191
#define IDB_EXITBTN_JP                  193
#define IDB_OPTIMIZE_BTN_JP             194
#define IDB_SOLUTIONBTN_JP              195
#define IDB_START_JP                    196
#define IDB_BACK_TH                     197
#define IDB_ERROR_BACK_TH               198
#define IDB_EXITBTN_TH                  199
#define IDB_OPTIMIZE_BTN_TH             200
#define IDB_SOLUTIONBTN_TH              201
#define IDB_START_TH                    202
#define IDD_OTPDLG                      203
#define IDB_LOGIN_ENTER_BTN_TH          204
#define IDB_LOGIN_ENTRY_BTN_TH          205
#define IDB_LOGIN_FINDID_BTN_TH         206
#define IDB_LOGIN_FINDPW_BTN_TH         207
#define IDB_LOGIN_ENTER_BTN_TW          210
#define IDB_LOGIN_ENTRY_BTN_TW          211
#define IDB_LOGIN_FINDID_BTN_TW         212
#define IDB_LOGIN_FINDPW_BTN_TW         213
#define IDB_BITMAP5                     214
#define IDB_LOGIN_TW                    214
#define IDB_LOGIN_TEXTBOX               215
#define IDD_DIALOG_                     216
#define IDD_DIALOG_WAITING              216
#define IDB_LOGIN_ENTER_BTN_US          217
#define IDB_LOGIN_ENTRY_BTN_US          219
#define IDB_LOGIN_FINDID_BTN_US         220
#define IDB_LOGIN_FINDPW_BTN_US         221
#define IDB_SOLUTIONBTN_US              222
#define IDB_BITMAP6                     223
#define IDB_LOGIN_US                    223
#define IDB_LOGIN_ID                    224
#define IDR_EU_ERRMSG_XML               232
#define IDB_BITMAP7                     233
#define IDB_ERROR_BACK_SA               233
#define IDB_BITMAP8                     234
#define IDB_EXITBTN_SA                  234
#define IDB_BITMAP9                     235
#define IDB_SOLUTIONBTN_SA              235
#define IDB_BITMAP10                    236
#define IDB_START_SA                    236
#define IDB_BITMAP11                    237
#define IDB_BACK_SA                     237
#define IDD_EXPLORER_DLG                238
#define IDB_CONFIRMBTN                  239
#define IDR_TXT_ERROR                   240
#define IDR_TXT_ERROR_EU                241
#define IDR_TXT_ERROR_ID                242
#define IDR_TXT_ERROR_NA                243
#define IDR_TXT_ERROR_SA                244
#define IDR_TXT_ERROR_TH                245
#define IDR_TXT_ERROR_TW                246
#define IDR_TXT7                        246
#define IDR_TXT1                        247
#define IDB_LOGIN_FINDPW_BTN_SEA        250
#define IDB_BITMAP12                    251
#define IDB_LOGIN_FINDID_BTN_SEA        251
#define IDC_BUTTON1                     1003
#define IDC_TEXT                        1006
#define IDC_PROGRESSBAR                 1007
#define IDC_EDIT1                       1008
#define IDC_ERROR_EDIT                  1008
#define IDC_LOGIN_EDIT_ID               1008
#define IDC_PWEDIT                      1008
#define ID_SOLUTION                     1009
#define IDC_OPTIMIZE_BTN                1010
#define IDC_CHECK1                      1011
#define IDC_CHECK_SHORTCUT              1011
#define IDC_CHECK_TOOLBAR               1012
#define IDC_BUTTON_DESCRIPTION          1013
#define IDC_START                       1014
#define IDC_EXPLORER1                   1015
#define ID_EXIT_BTN                     1016
#define IDC_X_BTN                       1017
#define IDC_LOGIN_X                     1018
#define IDC_LOGIN_IDSAVE                1019
#define IDC_LOGIN_ENTER                 1020
#define IDC_LOGIN_ENTRY                 1021
#define IDC_LOGIN_FIND_ID               1022
#define IDC_LOGIN_EDIT_PW               1023
#define IDC_LOGIN_FIND_PW               1024
#define IDC_COMBO1                      1025
#define IDC_2                           1026
#define IDC_3                           1027
#define IDC_4                           1028
#define IDC_6                           1029
#define IDC_5                           1030
#define IDC_10                          1031
#define IDC_9                           1032
#define IDC_8                           1033
#define IDC_7                           1034
#define IDC_SEND                        1035
#define IDC_CANCEL                      1036
#define IDC_1                           1037
#define IDC_DELETE                      1038
#define IDC_LOGIN_TEXT                  1039
#define IDC_STATIC_WAITING              1040
#define IDC_PROGRESS1                   1041
#define IDC_EXPLORER_IMG                1042
#define IDC_PROGRESSBAR_OPTIMIZATION    1043
#define IDC_GA_EXPLORER                 1043
#define IDC_GARENA_COMBO                1044
#define IDC_OK                          1045
#define IDC_BTN_OK                      1045
#define IDC_MIGRATIONL                  1046
#define IDC_BTN_OK2                     1046
#define IDC_MIGRATIONR                  1047
#define IDB_MIGRATION_L                 1048
#define IDB_MIGRATION_R                 1049
#define IDB_MIGRATION_BACK              1050
#define ID_EXPLORER_EXIT_BTN            1051
#define IDC_EXPLORER_EDIT               1052
#define IDB_LOGIN_X_BTN2                1053
#define IDC_EXPLORER_X                  1054
#define IDC_SYSLINK1                    1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
