[ChangeInfo]
; 기본값을 100으로 한다.
ChangeCash = 2.3571
etcitem = 100
decoItem = 100

Class_Max = 3

Class_1Start = 1
Class_1End = 1
Class_1Rate = 70

Class_2Start = 2
Class_2End = 10
Class_2Rate = 50

Class_32Start = 20
Class_3End = 30
Class_3Rate = 10

normal_char = 100
rare_char = 100
premium_char = 100

Change = 1
