#pragma once

#define IDC_CONNECT					(WM_USER+1)
#define IDC_DISCONNECT				(WM_USER+2)
#define IDC_RECEIVE					(WM_USER+3)

#define IDC_SERVICE_MONITOR			(WM_USER+100)
#define IDC_SERVICE_PLAY			(WM_USER+101)
#define IDC_SERVICE_STOP			(WM_USER+102)
#define IDC_SERVICE_UNINSTALL		(WM_USER+103)
#define IDC_SERVICE_ADD_IP			(WM_USER+104)
#define IDC_SERVICE_DELETE_IP		(WM_USER+105)
#define IDC_SERVICE_PLAY_CONSOLE	(WM_USER+106)
#define IDC_SERVICE_STOP_CONSOLE	(WM_USER+107)
#define IDC_SERVICE_SPREAD			(WM_USER+108)
#define WM_AUTOMATIC				(WM_USER+109)
#define IDC_SERVICE_REFRESH			(WM_USER+110)
#define IDC_SERVICE_PLAYALL			(WM_USER+111)
#define IDC_SERVICE_STOPALL			(WM_USER+112)
#define IDC_SERVICE_INSTALL			(WM_USER+113)
#define IDC_SERVICE_REBOOT			(WM_USER+114)
#define IDC_SERVICE_FILESYNC		(WM_USER+115)
#define IDC_SERVICE_FILEBACKUP		(WM_USER+116)
#define IDC_SERVICE_FILEREMOVE		(WM_USER+117)

namespace ECOMMAND
{
	enum command
	{
		REBOOT=3,
		FILESYNC,
		FILEBACKUP,
		FILEREMOVE,
		PLAYALL,
		STOPALL,
		SERVICEINSTALL,
		REFRESH,
		PLAYSERVICE,
		STOPSERVICE,
		PLAYCONSOLE,
		STOPCONSOLE,
		UNINSTALL,
		WATCHDOG,
		MONITOR,
	};
}
