#pragma once

enum BrowsePageType
{
	BROWSE_DEFAULT,
	BROWSE_SINGLE,
	BROWSE_FORMALITY_ENTRY,	
	BROWSE_GUILD_MARK,
	BROWSE_FILL_CASH,
	BROWSE_CASH_ENTRY,
};

enum BrowsePageSubType
{
	BROWSE_SUB_DEFAULT,
	BROWSE_SUB_QUEATER,
	BROWSE_SUB_GUILD,
	BROWSE_SUB_FORMALITY_ENTRY,
	BROWSE_SUB_GUILD_MARK,
	BROWSE_SUB_FILL_CASH,
	BROWSE_SUB_CASH_ENTRY,
};

