#include "ioLocalTaiwanLanguage.h"

namespace TaiwanLanguage
{

const char *GetMemTextList()
{
	return "|EXE_CAutoUpgradeApp::IsDuplication_1|\r\n\r\n      [王牌對決]已執?\r\n\r\n      請結?[王牌對決]後再執?\r\n\r\n\r\n      (錯?編號:201)|"
		"|EXE_CAutoUpgradeDlg::OnCopyData_1|連線遊戲?服器中.|"
		"|EXE_CAutoUpgradeDlg::OnCopyData_2|UDP 連線中|"
		"|EXE_CAutoUpgradeDlg::OnCopyData_3|遊戲?服器連線失敗|"
		"|EXE_CAutoUpgradeDlg::OnTimer_1|遊戲執?中|"
		"|EXE_CAutoUpgradeDlg::OnTimer_2|10分鐘內遊戲執?失敗\r\n(錯?編號:210)|"
		"|EXE_CAutoUpgradeDlg::OnTimer_3|遊戲?服器連線失敗|"
		"|EXE_CAutoUpgradeDlg::OnTimer_4|最佳化中|"
		"|EXE_CAutoUpgradeDlg::OnTimer_5|最佳化中|"
		"|EXE_CAutoUpgradeDlg::OnTimer_6|遊戲自動?始|"
		"|EXE_CAutoUpgradeDlg::OnTimer_7|遊戲自動?始|"
		"|EXE_CAutoUpgradeDlg::OnTimer_8|執?主?式失敗\r\n(錯?編號:226)|"
		"|EXE_CAutoUpgradeDlg::OnTimer_9|執?主?式失敗|"
		"|EXE_CAutoUpgradeDlg::SetWantEndDialog_1|結?中，請稍?.|"
		"|EXE_Help::CheckRightHDDSpace_1|?新王牌對決需要至少%1MB以上的\r\n硬碟空間。\r\n(錯?編號:207)\r\n\r\n?空間:%2M, 剩餘空間:%3M, 王牌對決所需求的空間:%4M|"
		"|EXE_Help::CheckDownloadedFile_1|檔??新失敗\r\n|"
		"|EXE_Help::CheckDownloadedFile_2|下載檔?錯?\r\n檔名:%1\r\n檔?CRC:%2, 檔?大小:%3,GetLastError:%4|"
		"|EXE_HTTPManager::_Run_1|?新檔讀取中|"
		"|EXE_HTTPManager::_Run_2|安裝的 DirectX版?不符\r\n請?新至最新版?DirectX\r\n請確?顯?卡驅動?式是?為最新版?\r\n(錯?編號:211)|"
		"|EXE_HTTPManager::_Run_3|%1號 iop ?啟失敗\r\n檔?刪除失敗\r\n檔名:%2, GetLastError:%3\r\n請?新安裝?式後執?\r\n(錯?編號:222)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_4|資?檔?下載失敗\r\n?新?服器擁擠\r\n請稍?再嘗試\r\n(錯?編號:203)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_5|檔?毀損\r\n?新?服器擁擠\r\n請稍?再試\r\n(錯?編號:215)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_6|資訊檔?解壓縮失敗\r\n請確??新檔同步是?有問題後\r\n ?新執?\r\n(錯?編號:204)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_7|資訊檔?分析失敗\r\n 請?新執??式\r\n(錯?編號:205)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_8|請確?硬碟空間\r\n硬碟空間是?充足\r\n確?完後\r\n再嘗試\r\n(錯?編號:223)\r\n\r\nGetLastError:%1|"
		"|EXE_HTTPManager::_Run_9|檔?下載?新失敗(?複100次都失敗).\r\n請?新執??式\r\n若?續發生問題\r\n請刪除王牌對決後檢查是?有病毒\r\n或是確?是?網路狀態??後?新安裝主?式\r\n(錯?編號:206)\r\n\r\n|"
		"|EXE_HTTPManager::DeleteGarbage_1|?新進?中 [%1/%2]|"
		"|EXE_HTTPManager::_RunAdmin_1|%1號檔按錯?\r\n\r\n%2|"
		"|EXE_HTTPManager::_RunAdmin_2|已完成|"
		"|EXE_HTTPManager::_RunAdmin_3|資?夾複製過?中發生錯?\r\n\r\n|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_1|錯??資?夾|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_2|錯?目標資?夾|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_3|資?夾複製中|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_4|已完成|"
		"|EXE_HTTPManager::AddPacFile_1|合成中:%1號檔?|"
		"|EXE_HTTPManager::AddPacFile_2|檔?合成錯?:%1.|"
		"|EXE_HTTPManager::AddPacFile_3|檔?合成錯?\r\n檔名:%1\r\n封?檔?內檔名:%2\r\n封?檔?:%3 , 檔? CRC:%4, GetLastError參數:%5, Exception:%6, |"
		"|EXE_HTTPManager::AddPacFile_4|檔?處理失敗\r\n檔名:%1\r\nGetLastError:%2, |"
		"|EXE_HTTPManager::CheckPac_1|錯? NULL.|"
		"|EXE_HTTPManager::CheckPac_2|確?使用的參數為NULL.\r\nGetLastError:%1\r\n|"
		"|EXE_HTTPManager::CheckPac_3|檔?檢查中:%1/%2號檔?[%3%%].|"
		"|EXE_HTTPManager::CopyVersionupFiles_1|manual patch:[%1%%].|"
		"|EXE_HTTPManager::CreateAllNewPacFile_1|%1號檔?最佳化失敗\r\n請?新執??式\r\n(錯?編號:212)\r\n\r\n%2|"
		"|EXE_HTTPManager::CreateNewPacFile_1|刪除舊檔?失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::CreateNewPacFile_2|儲存錯?|"
		"|EXE_HTTPManager::CreateNewPacFile_3|?啟新檔?失敗\r\n|"
		"|EXE_HTTPManager::CreateNewPacFile_4|錯?檔? NULL.|"
		"|EXE_HTTPManager::CreateNewPacFile_5|處理檔?所需 iop檔?參數為 NULL\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::CreateNewPacFile_6|錯?檔?|"
		"|EXE_HTTPManager::CreateNewPacFile_7|處理檔?所需 iop檔??始失敗\r\n檔名:%1\r\nGetLastError:%2,Exception:%3|"
		"|EXE_HTTPManager::CreateNewPacFile_8|錯?檔?|"
		"|EXE_HTTPManager::CreateNewPacFile_9|處理檔?所需 iop檔?資訊初始化失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::CreateNewPacFile_10|錯?檔? NULL 2.|"
		"|EXE_HTTPManager::CreateNewPacFile_11|處理檔?所需 iop檔?參數為 NULL \r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::CreateNewPacFile_12|錯?檔?2.|"
		"|EXE_HTTPManager::CreateNewPacFile_13|處理檔?所需 iop檔??始失敗\r\n檔名:%1\r\nGetLastError:%2, 檔?CRC:%3, Exception:%4|"
		"|EXE_HTTPManager::CreateNewPacFile_14|最佳化中:%1/%2號檔?[%3%%].|"
		"|EXE_HTTPManager::CreateNewPacFile_15|錯?檔?資訊|"
		"|EXE_HTTPManager::CreateNewPacFile_16|處理檔?所需舊iop檔?讀取失敗\r\n檔名:%1\r\nGetLastError:%2,array:%3,Exception:%4|"
		"|EXE_HTTPManager::CreateNewPacFile_17|錯?檔?資訊|"
		"|EXE_HTTPManager::CreateNewPacFile_18|處理檔?所需舊iop檔?讀取失敗\r\n檔名:%1\r\n檔?hash:%2,檔?index:%3,檔?壓縮大小:%4,檔?大小:%5,GetLastError:%6,array:%7,Exception:%8|"
		"|EXE_HTTPManager::CreateNewPacFile_19|檔?合成錯?|"
		"|EXE_HTTPManager::CreateNewPacFile_20|新 rs.iop裡檔?合成失敗\r\n檔名:%1\r\n檔?hash:%2, 檔?index:%3, 檔?壓縮大小:%4, 檔?大小:%5,GetLastError:%6, array:%7,Exception:%8|"
		"|EXE_HTTPManager::CreateNewPacFile_21|錯?檔?大小|"
		"|EXE_HTTPManager::CreateNewPacFile_22|處理檔?所需舊iop檔?資訊大小為0\r\n檔名:%1\r\n檔?hash:%2,檔?index:%3,檔?壓縮大小:%4,檔?大小:%5,GetLastError:%6,array:%7,Exception:%8|"
		"|EXE_HTTPManager::CreateNewPacFile_23|錯?檔?複製|"
		"|EXE_HTTPManager::CreateNewPacFile_24|新iop 複製錯?\r\n檔名:%1\r\n新檔名:%2\r\nGetLastError:%3|"
		"|EXE_HTTPManager::CreateNewPacFile_25|錯?檔?刪除|"
		"|EXE_HTTPManager::CreateNewPacFile_26|複製新檔?完成後刪除舊檔失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::DownLoadProcess_1|下載中:%1號檔?|"
		"|EXE_HTTPManager::DownLoadProcess_2|錯? OpenUrl:%1.|"
		"|EXE_HTTPManager::DownLoadProcess_3|OpenURL失敗\r\n檔名:%1\r\n錯?:%2|"
		"|EXE_HTTPManager::DownLoadProcess_4|錯? OpenUrl NULL:%1.|"
		"|EXE_HTTPManager::DownLoadProcess_5|CInternetFile參數為 NULL\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::DownLoadProcess_6|檔?下載?刪除舊檔失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::DownLoadProcess_7|檔??啟錯?:%1.|"
		"|EXE_HTTPManager::DownLoadProcess_8|?啟檔?前刪除舊檔失敗\r\n|"
		"|EXE_HTTPManager::DownLoadProcess_9|%1 下載中 [%2%%].|"
		"|EXE_HTTPManager::DownLoadProcess_10|錯?檔?寫入:%1.|"
		"|EXE_HTTPManager::DownLoadProcess_11|檔?儲存前刪除舊檔失敗\r\n|"
		"|EXE_HTTPManager::DownLoadProcess_12|錯?檔?獲取:%1.|"
		"|EXE_HTTPManager::DownLoadProcess_13|檔?儲存前取得檔?失敗\r\n|"
		"|EXE_HTTPManager::FileCopy_1|錯?檔?複製:%1.|"
		"|EXE_HTTPManager::FileCopy_2|檔?複製失敗\r\n檔名:%1\r\n新檔名:%2\r\nGetLastError:%3, |"
		"|EXE_HTTPManager::GetUpdateFile_1|確?下載中|"
		"|EXE_HTTPManager::GetUpdateFile_2|?新確?中[%1%%].|"
		"|EXE_HTTPManager::InitPac_1|記憶體分割失敗\r\n請?新執??式\r\n(錯?編號:213)\r\n\r\narray:%1, GetLastError:%2|"
		"|EXE_HTTPManager::OpenAllBigPacForGarbageSize_1|%1號 iop ?啟失敗\r\n檔名:%2, GetLastError:%3\r\n請?新執??式\r\n(錯?編號:225)\r\n\r\n|"
		"|EXE_HTTPManager::ParseDeleteFileList_1|檔?刪除分析中|"
		"|EXE_HTTPManager::ParsePatchFile_1|檔??啟失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::ParsePatchFile_2|檔?刪除失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::ProcessCheckPac_1|主?式發生問題\r\n\r\n請按[確?]檢查?部檔?\r\n\r\n若還是有錯?請?新下載主?式|"
		"|EXE_HTTPManager::ProcessCheckPac_2|主?式發生錯?\r\n\r\n主?式?新下載|"
		"|EXE_HTTPManager::ProcessCheckPac_3|%1號 iop ?啟失敗\r\n檔?刪除失敗\r\n檔名:%2, GetLastError:%3\r\n請?新執??式\r\n(錯?編號:224)\r\n\r\n|"
		"|EXE_HTTPManager::ProcessNewPacFile_1|已完成最佳化|"
		"|EXE_HTTPManager::ProcessNewPacFile_2|已完成最佳化|"
		"|EXE_HTTPManager::Run_1|發生意?錯?\r\n 請?新執??式\r\n(錯?編號:209)\r\n\r\n|"
		"|EXE_HTTPManager::SetTextWaitNewPac_1|最佳化中[%1]|"
		"|EXE_HTTPManager::SetupFull_1|%1號檔?發生錯?\r\n\r\n%2|"
		"|EXE_HTTPManager::SetupFull_2|安裝版?刪除??失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::SetupFull_3|安裝版??啟檔?失敗\r\n|"
		"|EXE_HTTPManager::SetupFull_4|檔??始錯?|"
		"|EXE_HTTPManager::SetupFull_5|安裝後%1號 iop檔?啟失敗\r\n檔名:%2\r\nGetLastError:%3, 檔?CRC:%4, Exception:%5, |"
		"|EXE_HTTPManager::StartGame_1|遊戲執?中|"
		"|EXE_HTTPManager::StartGame_2|登入有??間已過期\r\n\r\n         請?新\r\n\r\n            進?登入|"
		"|EXE_HTTPManager::StartGame_3|遊戲自動?始[%1]|"
		"|EXE_HTTPManager::StartGame_4|請按?始鍵執?遊戲|"
		"|EXE_HTTPManager::StartGame_5|Web Broker Version is low. Please restart the game.|"
		"|EXE_HTTPManager::StartGame_6|Web Broker Error!!|"
		"|EXE_HTTPManager::UnFull_1|錯??定NULL.|"
		"|EXE_HTTPManager::UnFull_2|安裝版?使用的參數為 NULL \r\nGetLastError:%1, |"
		"|EXE_HTTPManager::UnFull_3|錯?安裝|"
		"|EXE_HTTPManager::UnFull_4|安裝版??啟失敗\r\n檔名:%1\r\nGetLastError:%2, 檔?CRC:%3, Exception:%4, |"
		"|EXE_HTTPManager::UnFull_5|錯?安裝|"
		"|EXE_HTTPManager::UnFull_6|安裝資訊讀取失敗\r\n檔名:%1\r\nGetLastError:%2, 檔?CRC:%3, 檔?array:%4, Exception:%5, |"
		"|EXE_HTTPManager::UnFull_7|解壓縮中:%1號檔?[%2%%].|"
		"|EXE_HTTPManager::UnFull_8|安裝版?刪除舊檔失敗\r\n檔名:%1\r\nGetLastError:%2, |"
		"|EXE_HTTPManager::UnFull_9|錯?安裝解除:%1.|"
		"|EXE_HTTPManager::UnFull_10|安裝版?解壓縮失敗\r\n檔名:%1\r\nGetLastError:%2, 安裝檔CRC:%3, array:%4, Exception:%5, |"
		"|EXE_HTTPManager::UnFull_11|安裝版?刪除失敗\r\n檔名:%1\r\nGetLastError:%2, |"
		"|EXE_HTTPManager::UnPac_1|錯?封? NULL.|"
		"|EXE_HTTPManager::UnPac_2|解封?所需 rs.iop檔?參數為 NULL\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::UnPac_3|檔??啟錯?|"
		"|EXE_HTTPManager::UnPac_4|解壓縮所需 rs.iop檔??啟失敗\r\n檔名:%1\r\nGetLastError:%2,Exception:%3|"
		"|EXE_HTTPManager::UnPac_5|錯?封?INIT.|"
		"|EXE_HTTPManager::UnPac_6|解壓封?所需 rs.iop檔?資訊初始化失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::UnPac_7|錯?封?資訊|"
		"|EXE_HTTPManager::UnPac_8|封?解壓縮所需rs.iop檔?資訊讀取失敗\r\n檔名:%1\r\nGetLastError:%2,array:%3,Exception:%4|"
		"|EXE_HTTPManager::UnPac_9|IOP解壓中:%1/%2號檔?[%3%%].|"
		"|EXE_HTTPManager::UnPac_10|解封?前刪除舊檔失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::UnPac_11|錯?解壓封?|"
		"|EXE_HTTPManager::UnPac_12|封?檔?解壓失敗\r\n檔名:%1\r\n檔?hash:%2,檔?index:%3,檔?壓縮大小:%4,GetLastError:%5,array:%6,Exception:%7|"
		"|EXE_HTTPManager::UnPacPieceFile_1|解壓中:%1號檔?|"
		"|EXE_HTTPManager::UnPacPieceFile_2|解壓前舊檔刪除失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::UnPacPieceFile_3|解壓檔?不存在\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::UnPacPieceFile_4|錯?檔?:%1.|"
		"|EXE_HTTPManager::UnPacPieceFile_5|解壓檔?失敗\r\n檔名:%1\r\n錯??傳參數:%2, 檔?CRC參數:%3, GetLastError參數:%4, Exception:%5|"
		"|EXE_HTTPManager::UnPacPieceFile_6|解壓檔?前刪除舊檔失敗\r\n檔名:%1\r\nGetLastError:%2|"
		"|EXE_HTTPManager::UpdateFileLoop_1|分析下載檔?資訊中|"
		"|EXE_HTTPManager::UpdateFileLoop_2|發生錯?，?新嘗試中:%1/%2.|"
		"|EXE_HTTPManager::UpdateOneFile_1|下載檔?發生錯?\r\n自動?新嘗試(??100次)\r\n若要結??式\r\n請按自動?新的X按鍵\r\n(錯?編號:218)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_2|下載檔?毀損錯?.:%1.|"
		"|EXE_HTTPManager::UpdateOneFile_3|下載檔?毀損\r\n?新?服器擁擠\r\n自動?新嘗試(??100次)\r\n若要結??式\r\n請按自動?新的X按鍵\r\n(錯?編號:216)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_4|下載檔?大小錯?|"
		"|EXE_HTTPManager::UpdateOneFile_5|檔?大小不?致\r\n檔名:%1\r\n?服器檔?大小:%2, 下載 檔?大小:%3, ?服器檔?CRC:%4, 已下載檔?CRC:%5|"
		"|EXE_HTTPManager::UpdateOneFile_6|下載檔?大小已變?\r\n?新檔資訊無法?新\r\n請確?是?有病毒\r\n若?續發生問題請?新安裝主?式|"
		"|EXE_HTTPManager::UpdateOneFile_7|?服器檔?大小:%1, 下載的檔?大小:%2, ?服器檔?CRC:%3|"
		"|EXE_HTTPManager::UpdateOneFile_8|檔?合成?發生錯?\r\n自動?新嘗試(??100次)\r\n若要結??式\r\n請按自動?新的X按鍵\r\n(錯?編號:219)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_9|?服器檔?大小:%1, 下載檔?大小:%2, ?服器檔?CRC:%3|"
		"|EXE_HTTPManager::UpdateOneFile_10|檔?解壓縮發生錯?\r\n自動?新嘗試(??100次)\r\n若要結??式\r\n請按自動?新的X按鍵\r\n(錯?編號:220)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_11|?服器檔?大小:%1, 下載檔?大小:%2, ?服器檔?CRC:%3|"
		"|EXE_HTTPManager::UpdateOneFile_12|檔?複製錯?\r\n自動?新嘗試(??100次)\r\n若要結??式\r\n請按自動?新的X按鍵\r\n(錯?編號:221)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_13|?服器檔?大小:%1, 下載檔?大小:%2|"
		"|EXE_HTTPManager::UpdateOneFile_14|版?安裝錯?\r\n自動?新嘗試(??100次)\r\n若要結??式\r\n請按自動?新的X按鍵\r\n(錯?編號:217)\r\n\r\n|"
		"|EXE_ioErrorDlg::ShowErrorDlg_1|Ver : %1\r\n--- 系統規? ---\r\n%2\r\n\r\n--- 系統訊? ---\r\n%3|"
		"|EXE_ioLoginDlg::FirstConnectServer_1|與%1?服器網路連線中.|"
		"|EXE_ioLoginDlg::OnTimer_1|%1?服器?應逾??連線到 %2?服器中.|"
		"|EXE_ioLoginDlg::OnTimer_2|%1?服器無?應故連線中止, 與%2?服器網路連線中.|"
		"|EXE_ioLoginDlg::SendServer_1|%1?服器的登入訊?傳送完畢，等待?服器?應中.|"
		"|EXE_ioLoginDlg::SetTextNetworkConnected_1|與%1?服器連線成?.|";
}

}