#include "ioLocalJapanLanguage.h"

namespace JapanLanguage
{

const char *GetMemTextList()
{
	return 	"|EXE_CAutoUpgradeApp::IsDuplication_1|\r\n\r\n      ロストサガがは既に実行中です。\r\n\r\n      ロストサガを終了した後実行してください。\r\n\r\n\r\n      (エラ?番号:201)|"
			"|EXE_CAutoUpgradeDlg::OnCopyData_1|ゲ??サ?バ?に接続中です。|"
			"|EXE_CAutoUpgradeDlg::OnCopyData_2|UDPを連結中です。|"
			"|EXE_CAutoUpgradeDlg::OnCopyData_3|ゲ??サ?バ?接続に失敗しました。|"
			"|EXE_CAutoUpgradeDlg::OnTimer_1|ゲ??が実行中です。|"
			"|EXE_CAutoUpgradeDlg::OnTimer_2|10分間ゲ??実行に失敗しました。\r\n(エラ?番号:210)|"
			"|EXE_CAutoUpgradeDlg::OnTimer_3|ゲ??サ?バ?接続に失敗しました。|"
			"|EXE_CAutoUpgradeDlg::OnTimer_4|最適化の確認中|"
			"|EXE_CAutoUpgradeDlg::OnTimer_5|最適化の確認中|"
			"|EXE_CAutoUpgradeDlg::OnTimer_6|ゲ??がス??トします。|"
			"|EXE_CAutoUpgradeDlg::OnTimer_7|ゲ??がス??トします。|"
			"|EXE_CAutoUpgradeDlg::OnTimer_8|クライアント実行に失敗しました。\r\n(エラ?番号:226)|"
			"|EXE_CAutoUpgradeDlg::OnTimer_9|クライアント実行に失敗しました。|"
			"|EXE_CAutoUpgradeDlg::SetWantEndDialog_1|クライアントが終了します。しばらくお待ちください。|"
			"|EXE_Help::CheckRightHDDSpace_1|ロストサガのアップデ?トの為には%１メガバイト以上の\r\n空き容量が必要です。\r\n(エラ?番号:207)\r\n\r\n全体サイズ:%2M、空き領域 :%3M、ロストサガ必要容量:%4M|"
			"|EXE_Help::CheckDownloadedFile_1|認証と完全性の確認のためのフ?イルオ?プンに失敗しました。\r\n|"
			"|EXE_Help::CheckDownloadedFile_2|?ウンロ?ドされたフ?イルはエラ?ペ?ジです。\r\nフ?イル名:%1\r\nフ?イルCRC:%2, フ?イルサイズ:%3,GetLastError:%4|"
			"|EXE_HTTPManager::_Run_1|ロ?カルパッ?情報読み取り中|"
			"|EXE_HTTPManager::_Run_2|設置されたDirectXのバ?ジョンが古いです。\r\n最新バ?ジョンのDirectXをインスト?ルしてください。\r\nグラフィックカ?ドのドライバ?も最新であるかご確認ください。\r\n(エラ?番号:211)|"
			"|EXE_HTTPManager::_Run_3|%１番目iop オ?プンが失敗し、\r\nフ?イル削除に失敗しました。\r\nフ?イル名:%2, GetLastError:%3\r\nプログラ?を実行しなおしてください。\r\n(エラ?番号:222)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_4|情報フ?イル?ウンロ?ドに失敗しました。\r\nパッ?サ?バ?が込み合っています。\r\nしばらくしてから、プログラ?を実行しなおしてください。\r\n(エラ?番号:203)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_5|情報フ?イルが壊れています。\r\nパッ?サ?バ?が込んでいる可?性があります。\r\nしばらくしてから、プログラ?を実行しなおしてください。\r\n(エラ?番号:215)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_6|情報フ?イルパックを解?できませんでした。\r\nパッ?フ?イルの同期化に問題がないか確認し、\r\n プログラ?を実行しなおしてください。\r\n(エラ?番号:204)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_7|情報フ?イルの分析に失敗しました。\r\n プログラ?を実行しなおしてください。\r\n(エラ?番号:205)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_8|ハ?ドディスクの空き領域確認に失敗しました。\r\nハ?ドディスクの空き領域が?分であることと\r\n見なして実行します。\r\n問題が続きますと、ハ?ドディスクの空き領域を確保してください。\r\n(エラ?番号:223)\r\n\r\nGetLastError:%1|"
			"|EXE_HTTPManager::_Run_9|フ?イル?ウンロ?ド及び更新に失敗しました。(100回リトライ)\r\nプログラ?を実行しなおしてください。\r\n問題が続く場合は、プログラ?のメニュ?から\r\nロストサガ削除を実行し、ウィルス検査を行ってください。\r\nなお、イン??ネット回線状態の確認もお願いします。\r\n(エラ?番号:206)\r\n\r\n|"
			"|EXE_HTTPManager::_RunAdmin_1|%1番パックフ?イルを解?中にエラ?が発生しました。\r\n\r\n%2|"
			"|EXE_HTTPManager::_RunAdmin_2|完了しました。|"
			"|EXE_HTTPManager::_RunAdmin_3|フォル??のコピ?中、エラ?が発生しました。\r\n\r\n|"
			"|EXE_HTTPManager::_RunOptionCopyFolder_1|エラ?元フォル??|"
			"|EXE_HTTPManager::_RunOptionCopyFolder_2|エラ?目的フォル??|"
			"|EXE_HTTPManager::_RunOptionCopyFolder_3|フォル??コピ?中です。|"
			"|EXE_HTTPManager::_RunOptionCopyFolder_4|完了しました。|"
			"|EXE_HTTPManager::AddPacFile_1|連結中です。:%1番目フ?イル。.|"
			"|EXE_HTTPManager::AddPacFile_2|エラ?フ?イルを連結中です。:%1.|"
			"|EXE_HTTPManager::AddPacFile_3|フ?イル連結失敗\r\nフ?イル名:%1\r\nパックフ?イル内のフ?イル名:%2\r\nパックフ?イルアレイ:%3 ,フ?イル CRC:%4, GetLastError値:%5, Exception:%6, |"
			"|EXE_HTTPManager::AddPacFile_4|フ?イル連結中です。 ?ウンロ?ドフ?イルの削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2, |"
			"|EXE_HTTPManager::CheckPac_1|エラ??ェックパック NULL.|"
			"|EXE_HTTPManager::CheckPac_2|?ェックに使用するパックの変数が NULLです。\r\nGetLastError:%1\r\n|"
			"|EXE_HTTPManager::CheckPac_3|フ?イル確認中:%1/%2番目フ?イル[%3%%]|"
			"|EXE_HTTPManager::CopyVersionupFiles_1|manual patch:[%1%%].|"
			"|EXE_HTTPManager::CreateAllNewPacFile_1|%1番目フ?イル。最適かに失敗しました。\r\n プログラ?を再起動してください。\r\n(エラ?番号:212)\r\n\r\n%2|"
			"|EXE_HTTPManager::CreateNewPacFile_1|新しいパックフ?イル製作のための以前フ?イル削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::CreateNewPacFile_2|エラ?保存ニュ?パック|"
			"|EXE_HTTPManager::CreateNewPacFile_3|新しいパックフ?イル生成オ?プンに失敗しました。\r\n|"
			"|EXE_HTTPManager::CreateNewPacFile_4|エラ??ニュ?パック NULL.|"
			"|EXE_HTTPManager::CreateNewPacFile_5|新しいパックフ?イル製作のための iopフ?イル変数が NULLです。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::CreateNewPacFile_6|エラ? オ?プン ニュ?パック|"
			"|EXE_HTTPManager::CreateNewPacFile_7|新しいパックフ?イル製作のための iopフ?イル オ?プンに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2,Exception:%3|"
			"|EXE_HTTPManager::CreateNewPacFile_8|エラ? ニュ?パック情報|"
			"|EXE_HTTPManager::CreateNewPacFile_9|新しいパックフ?イル製作のための iopフ?イル 情報初期化に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::CreateNewPacFile_10|エラ? ニュ?パック NULL 2.|"
			"|EXE_HTTPManager::CreateNewPacFile_11|新しく製作する iop変数が NULLです。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::CreateNewPacFile_12|エラ? オ?プン ニュ?パック2.|"
			"|EXE_HTTPManager::CreateNewPacFile_13|新しく製作する iop フ?イル オ?プンに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2,フ?イルCRC:%3, Exception:%4|"
			"|EXE_HTTPManager::CreateNewPacFile_14|最適化中:%1/%2番目フ?イル[%3%%]|"
			"|EXE_HTTPManager::CreateNewPacFile_15|エラ? ニュ?パック フ?イル情報|"
			"|EXE_HTTPManager::CreateNewPacFile_16|新しいパックフ?イル製作のための、以前 iopフ?イル情報の読み取りに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2,アレイ:%3,Exception:%4|"
			"|EXE_HTTPManager::CreateNewPacFile_17|エラ? ニュ?パック フ?イルデ??|"
			"|EXE_HTTPManager::CreateNewPacFile_18|新しいパックフ?イル製作のための、以前 iopフ?イル情報の読み取りに失敗しました。 \r\nフ?イル名:%1\r\nフ?イルハッシュ:%2,フ?イルインデックス:%3,フ?イル圧縮サイズ:%4,フ?イルサイズ:%5,GetLastError:%6,アレイ:%7,Exception:%8|"
			"|EXE_HTTPManager::CreateNewPacFile_19|エラ? ニュ?パックフ?イル連結中|"
			"|EXE_HTTPManager::CreateNewPacFile_20|新しいrs.iopにフ?イル連結に失敗しました。\r\nフ?イル名:%1\r\nフ?イルハッシュ:%2,フ?イルインデックス:%3,フ?イル圧縮サイズ:%4,フ?イルサイズ:%5,GetLastError:%6,アレイ:%7,Exception:%8|"
			"|EXE_HTTPManager::CreateNewPacFile_21|エラ? ニュ?パックサイズ|"
			"|EXE_HTTPManager::CreateNewPacFile_22|新しいパックフ?イル製作のための、以前iop フ?イルデ??サイズが 0です。\r\nフ?イル名:%1\r\nフ?イルハッシュ:%2,フ?イルインデックス:%3,フ?イル圧縮サイズ:%4,フ?イルサイズ:%5,GetLastError:%6,アレイ:%7,Exception:%8|"
			"|EXE_HTTPManager::CreateNewPacFile_23|エラ? ニュ?パック コピ?|"
			"|EXE_HTTPManager::CreateNewPacFile_24|新しい iopコピ?に失敗しました。\r\nフ?イル名:%1\r\n新しいフ?イル名:%2\r\nGetLastError:%3|"
			"|EXE_HTTPManager::CreateNewPacFile_25|エラ? ニュ?パック削除|"
			"|EXE_HTTPManager::CreateNewPacFile_26|ニュ?フ?イルコピ?完了後、コピ?前ニュ?フ?イル削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::DownLoadProcess_1|?ウンロ?ド中:%1番目フ?イル|"
			"|EXE_HTTPManager::DownLoadProcess_2|エラ? OpenUrl:%1|"
			"|EXE_HTTPManager::DownLoadProcess_3|OpenURLに失敗しました。\r\nフ?イル名:%1\r\nエラ?:%2|"
			"|EXE_HTTPManager::DownLoadProcess_4|エラ? OpenUrl NULL:%1.|"
			"|EXE_HTTPManager::DownLoadProcess_5|CInternetFile日値が NULLです。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::DownLoadProcess_6|フ?イル?ウンロ?ド中、以前フ?イルの削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::DownLoadProcess_7|エラ? フ?イル オ?プン:%1|"
			"|EXE_HTTPManager::DownLoadProcess_8|フ?イル保存のためのフ?イルオ?プンに失敗しました。\r\n|"
			"|EXE_HTTPManager::DownLoadProcess_9|%1 ?ウンロ?ド中: [%2%%]|"
			"|EXE_HTTPManager::DownLoadProcess_10|エラ? フ?イル上書き:%1|"
			"|EXE_HTTPManager::DownLoadProcess_11|フ?イル保存のためのフ?イル上書きに失敗しました。\r\n|"
			"|EXE_HTTPManager::DownLoadProcess_12|エラ?フ?イル受け取り:%1|"
			"|EXE_HTTPManager::DownLoadProcess_13|フ?イル保存のためのフ?イル受け取りに失敗しました。\r\n|"
			"|EXE_HTTPManager::FileCopy_1|エラ? フ?イルコピ?:%1|"
			"|EXE_HTTPManager::FileCopy_2|フ?イルコピ?に失敗しました。\r\nフ?イル名:%1\r\n新しいフ?イル名:%2\r\nGetLastError:%3, |"
			"|EXE_HTTPManager::GetUpdateFile_1|?ウンロ?ド確認中|"
			"|EXE_HTTPManager::GetUpdateFile_2|アップデ?ト確認中[%1%%].|"
			"|EXE_HTTPManager::InitPac_1|パックライブラリ?メモリの割り当てに失敗しました。\r\nプログラ?を再起動してください。\r\n(エラ?番号:213)\r\n\r\nアレイ:%1, GetLastError:%2|"
			"|EXE_HTTPManager::OpenAllBigPacForGarbageSize_1|%1番目 iop オ?プンに失敗しました。\r\nフ?イル名:%2, GetLastError:%3\r\nプログラ?を再起動してください。\r\n(エラ?番号:225)\r\n\r\n|"
			"|EXE_HTTPManager::ParseDeleteFileList_1|削除フ?イル分析中|"
			"|EXE_HTTPManager::ParsePatchFile_1|パ?シングのためのフ?イルオ?プンに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::ParsePatchFile_2|パ?シング後、以前フ?イル削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::ProcessCheckPac_1|クライアントフ?イルに問題が発見されました。\r\n\r\n[はい]を押すと全体フ?イルを検査し\r\n\r\nエラ?が発見されたらクライアントを再?ウンロ?ドします。|"
			"|EXE_HTTPManager::ProcessCheckPac_2|クライアントフ?イルでエラ?が発見されました。\r\n\r\nクライアントを再?ウンロ?ドします。|"
			"|EXE_HTTPManager::ProcessCheckPac_3|%1番目 iop オ?プンに失敗され\r\nフ?イル削除に失敗しました。\r\nフ?イル名:%2, GetLastError:%3\r\nプログラ?を再起動してください。\r\n(エラ?番号:224)\r\n\r\n|"
			"|EXE_HTTPManager::ProcessNewPacFile_1|すでに最適化されました。|"
			"|EXE_HTTPManager::ProcessNewPacFile_2|すでに最適化されました。|"
			"|EXE_HTTPManager::Run_1|メインル?プに例外エラ?が発生しました。\r\n プログラ?を再起動してください。\r\n(エラ?番号:209)\r\n\r\n|"
			"|EXE_HTTPManager::SetTextWaitNewPac_1|最適化の確認中[%1]|"
			"|EXE_HTTPManager::SetupFull_1|%１番パックフ?イルをオ?プンする間にエラ?が発生しました。\r\n\r\n%2|"
			"|EXE_HTTPManager::SetupFull_2|設置バ?ジョンのバ?ジョン情報削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::SetupFull_3|設置バ?ジョンのバ?ジョン情報フ?イルのオ?プンに失敗しました。\r\n|"
			"|EXE_HTTPManager::SetupFull_4|エラ?パックフ?イルのオ?プン|"
			"|EXE_HTTPManager::SetupFull_5|設置後、%1番目 iopフ?イル オ?プンに失敗しました。\r\nフ?イル名:%2\r\nGetLastError:%3, フ?イルCRC:%4, Exception:%5, |"
			"|EXE_HTTPManager::StartGame_1|ゲ??の実行中です。|"
			"|EXE_HTTPManager::StartGame_2|ログインキ?の有効時間が切れました。\r\n\r\n         安全にログインするため\r\n\r\n再ログインしてください。|"
			"|EXE_HTTPManager::StartGame_3|ゲ??がス??トします。[%1]|"
			"|EXE_HTTPManager::UnFull_1|エラ?フル設置 NULL|"
			"|EXE_HTTPManager::UnFull_2|設置バ?ジョンに使われるパック変数がNULLです。\r\nGetLastError:%1, |"
			"|EXE_HTTPManager::UnFull_3|エラ?フル設置オ?プン|"
			"|EXE_HTTPManager::UnFull_4|設置バ?ジョン オ?プンに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2, フ?イルCRC:%3, Exception:%4, |"
			"|EXE_HTTPManager::UnFull_5|エラ? フル設置情報|"
			"|EXE_HTTPManager::UnFull_6|設置情報の読み取りに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2,フ?イルCRC:%3, フ?イルアレイ:%4, Exception:%5, |"
			"|EXE_HTTPManager::UnFull_7|圧縮を解?中:%1番目フ?イル。[%2%%].|"
			"|EXE_HTTPManager::UnFull_8|設置バ?ジョンの以前フ?イル削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2, |"
			"|EXE_HTTPManager::UnFull_9|エラ?フル設置の解?:%1.|"
			"|EXE_HTTPManager::UnFull_10|設置バ?ジョン圧縮の解?に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2, 設置フ?イルCRC:%3,アレイ:%4, Exception:%5, |"
			"|EXE_HTTPManager::UnFull_11|設置バ?ジョン削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2, |"
			"|EXE_HTTPManager::UnPac_1|エラ? フルパック NULL|"
			"|EXE_HTTPManager::UnPac_2|パックフ?イルを解?するための rs.iopフ?イル変数が NULLです。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::UnPac_3|エラ?フルパック オ?プン|"
			"|EXE_HTTPManager::UnPac_4|パックフ?イル解?するための rs.iopフ?イルのオ?プンに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2,Exception:%3|"
			"|EXE_HTTPManager::UnPac_5|エラ?フルパック INIT|"
			"|EXE_HTTPManager::UnPac_6|パックフ?イルを解?するためのrs.iopフ?イル情報の初期化に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::UnPac_7|エラ?フルパック情報|"
			"|EXE_HTTPManager::UnPac_8|パックフ?イルを解?するための以前 rs.iopフ?イル情報の読み取りに失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2,アレイ:%3,Exception:%4|"
			"|EXE_HTTPManager::UnPac_9|IOPを解?中:%1/%2番目フ?イル[%3%%].|"
			"|EXE_HTTPManager::UnPac_10|パックフ?イルを解?するための以前フ?イル削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::UnPac_11|エラ?フルパック解?|"
			"|EXE_HTTPManager::UnPac_12|パックフ?イル解?のためのフ?イル解?に失敗しました。\r\nフ?イル名:%1\r\nフ?イルハッシュ:%2,フ?イルインデックス:%3,フ?イル圧縮サイズ:%4,GetLastError:%5,アレイ:%6,Exception:%7|"
			"|EXE_HTTPManager::UnPacPieceFile_1|圧縮を解?中:%１番目フ?イル|"
			"|EXE_HTTPManager::UnPacPieceFile_2|単品圧縮解?で以前フ?イル削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::UnPacPieceFile_3|単品圧縮解?で圧縮解?フ?イルが存在しません。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::UnPacPieceFile_4|エラ?単品アンパック:%1.|"
			"|EXE_HTTPManager::UnPacPieceFile_5|単品フ?イルの圧縮解?に失敗しました。\r\nフ?イル名:%1\r\nエラ?戻り値:%2,フ?イルCRC値:%3, GetLastError値:%4, Exception:%5|"
			"|EXE_HTTPManager::UnPacPieceFile_6|単品圧縮解?で?ウンロ?ドフ?イル削除に失敗しました。\r\nフ?イル名:%1\r\nGetLastError:%2|"
			"|EXE_HTTPManager::UpdateFileLoop_1|?ウンロ?ド対象フ?イル分析中|"
			"|EXE_HTTPManager::UpdateFileLoop_2|エラ?発生で再起動中:%1/%2.|"
			"|EXE_HTTPManager::UpdateOneFile_1|フ?イル?ウンロ?ドにエラ?が発生しました。\r\n自動的に再起動を始めます。(総100回)\r\nプログラ?を終了するためには\r\n自動アップデ?トの X??ンをクリックしてください。\r\n(エラ?番号:218)\r\n\r\n|"
			"|EXE_HTTPManager::UpdateOneFile_2|エラ? ?ウンロ?ドフ?イル損傷:%1.|"
			"|EXE_HTTPManager::UpdateOneFile_3|?ウンロ?ドされたフ?イルが損傷されました。\r\nパッ?サ?バ?が混雑しています。\r\n自動的に再起動を始めます。(総100回)\r\nプログラ?を終了するためには\r\n自動アップデ?トの X??ンをクリックしてください。\r\n(エラ?番号:216)\r\n\r\n|"
			"|EXE_HTTPManager::UpdateOneFile_4|エラ??ウンロ?ドフ?イルのサイズの問題|"
			"|EXE_HTTPManager::UpdateOneFile_5|フ?イルサイズが異なります。\r\nフ?イル名:%1\r\nサ?バ?フ?イルサイズ:%2,?ウンロ?ドしたフ?イルサイズ:%3,サ?バ?フ?イルCRC:%4,?ウンロ?ドしたフ?イルCRC:%5|"
			"|EXE_HTTPManager::UpdateOneFile_6|?ウンロ?ドしたフ?イルのサイズが変更されました。\r\nパッ?情報フ?イルがまだ更新されてなかったか若しくは\r\nウィルスに感染された可?性が有ります。\r\n問題が続きましたら、下記の通りに実行してください。\r\n\r\n1. [LostSaga]の設置されたフォル??削除\r\n Internet Explore7は ツ?ル->イン??ネットオプション->全般?ブ->削除->全て削除->[追加??で保存したフ?イル及び設定を全て削除]?ェック->はい\r\n   Internet Explore 6はツ?ル->イン??ネットオプション->全般?ブ->cookie削除->確認\r\nツ?ル->イン??ネットオプション->全般?ブ->フ?イル削除->[オフライン?目を全て削除]?ェック->|"
			"|EXE_HTTPManager::UpdateOneFile_7|サ?バ?フ?イルサイズ:%1,?ウンロ?ドしたフ?イルサイズ:%2,サ?バ?フ?イルCRC:%3|"
			"|EXE_HTTPManager::UpdateOneFile_8|フ?イルの連結中にエラ?が発生しました。\r\n自動的に再起動を始めます。(総100回)\r\nプログラ?を終了するためには\r\n自動アップデ?トの X??ンをクリックしてください。\r\n(エラ?番号:219)\r\n\r\n|"
			"|EXE_HTTPManager::UpdateOneFile_9|ｓ?バ?フ?イルサイズ:%1,?ウンロ?ドしたフ?イルサイズ:%2,ｓ?バ?フ?イルCRC:%3|"
			"|EXE_HTTPManager::UpdateOneFile_10|が単品フ?イル圧縮を解?するにエラ?が発生しました。\r\n自動的に再起動を始めます。(総100回)\r\nプログラ?を終了するためには\r\n自動アップデ?トの X??ンをクリックしてください。\r\n(エラ?番号:220)\r\n\r\n|"
			"|EXE_HTTPManager::UpdateOneFile_11|サ?バ?フ?イルサイズ:%1,?ウンロ?ドしたフ?イルサイズ:%2,サ?バ?フ?イルCRC:%3|"
			"|EXE_HTTPManager::UpdateOneFile_12|フ?イルコピ?中 エラ?が発生しました。\r\n自動的に再起動を始めます。(総100回)\r\nプログラ?を終了するためには\r\n自動アップデ?トの X??ンをクリックしてください。\r\n(エラ?番号:221)\r\n\r\n|"
			"|EXE_HTTPManager::UpdateOneFile_13|サ?バ?フ?イルサイズ:%1,?ウンロ?ドしたフ?イルサイズ:%2|"
			"|EXE_HTTPManager::UpdateOneFile_14|フルバ?ジョン設置に失敗しました。\r\n自動的に再起動を始めま'す。(総100回)\r\nプログラ?を終了するためには\r\n自動アップデ?トの X??ンをクリックしてください。\r\n(エラ?番号:217)\r\n\r\n|"
			"|EXE_ioErrorDlg::ShowErrorDlg_1|Ver : %1\r\n--- システ?仕様 ---\r\n%2\r\n\r\n--- エラ?情報 ---\r\n%3|";
}

}