#include "ioLocalThailandLanguage.h"

namespace ThailandLanguage
{

const char *GetMemTextList()
{
	return "|EXE_CAutoUpgradeApp::IsDuplication_1|\r\n\r\n      [Lost Saga] is running.\r\n\r\n      Close [Lost Saga] and try again.\r\n\r\n\r\n      (error code:201)|"
		"|EXE_CAutoUpgradeDlg::OnCopyData_1|Connecting to the Lost Saga server...|"
		"|EXE_CAutoUpgradeDlg::OnCopyData_2|Connecting to UDP...|"
		"|EXE_CAutoUpgradeDlg::OnCopyData_3|Failed connecting to the Lost Saga server.|"
		"|EXE_CAutoUpgradeDlg::OnTimer_1|Lost Saga is running...|"
		"|EXE_CAutoUpgradeDlg::OnTimer_2|Lost Saga was unable to launch for 10 minutes.\r\n(error code:210)|"
		"|EXE_CAutoUpgradeDlg::OnTimer_3|Failed connecting to the Lost Saga server.|"
		"|EXE_CAutoUpgradeDlg::OnTimer_4|Verifying optimization...|"
		"|EXE_CAutoUpgradeDlg::OnTimer_5|Verifying optimization...|"
		"|EXE_CAutoUpgradeDlg::OnTimer_6|Lost Saga will be started automatically.|"
		"|EXE_CAutoUpgradeDlg::OnTimer_7|Lost Saga will be started automatically.|"
		"|EXE_CAutoUpgradeDlg::OnTimer_8|Failed to launch the Lost Saga client.\r\n(error code:226)|"
		"|EXE_CAutoUpgradeDlg::OnTimer_9|Failed to lanunch the Lost Saga client.|"
		"|EXE_CAutoUpgradeDlg::SetWantEndDialog_1|Exiting... Please wait.|"
		"|EXE_Help::CheckRightHDDSpace_1|Updating Lost Saga requires %1 MB or more\r\nfree space in your hard disk.\r\n(error code:207)\r\n\r\nTotal: %2 MB, Free: %3 MB, Required: %4 MB|"
		"|EXE_Help::CheckDownloadedFile_1|Unable to open files for integrity tests.\r\n|"
		"|EXE_Help::CheckDownloadedFile_2|The downloaded file contains webpage errors.\r\nFile name: %1\r\nFileCRC: %2, Size: %3,GetLastError: %4|"
		"|EXE_HTTPManager::_Run_1|Retrieving local patch information...|"
		"|EXE_HTTPManager::_Run_2|The version of the currently installed DirectX is not up-to-date.\r\nPlease install the latest version of DirectX.\r\nMake sure that you have the latest graphics card driver installed.\r\n(error code:211)|"
		"|EXE_HTTPManager::_Run_3|Unable to open %1th iop.\r\nFailed to delete the file.\r\nFile name: %2, GetLastError: %3\r\nPlease run the program again.\r\n(error code:222)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_4|Failed to download the information file.\r\nThe patch server might be busy.\r\nPlease run the program again.\r\n(error code:203)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_5|The data file is corrupted.\r\nThe patch server might be busy.\r\nPlease run the program later.\r\n(error code:215)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_6|Failed to extract the information file package.\r\nMake sure that patch file is correctly synchronized and\r\nrun the program again.\r\n(error code:204)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_7|Failed to parse the information file.\r\n Please run the program again.\r\n(error code:205)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_8|The hard disk space function did not return the value.\r\nThe program will assume that there are enough free space\r\nin the hard disk and proceed accordingly.\r\nPlease secure more hard disk space if the problem persists.\r\n(error code: 223)\r\n\r\nGetLastError:%1|"
		"|EXE_HTTPManager::_Run_9|Unable to download and update the file (failed 100 times).\r\nPlease run the program again.\r\nIf the problem persists, remove Lost Saga from\r\nPrograms and scan the files for viruses.\r\nMake sure that you are connected to the Internet.\r\n(error code: 206)\r\n\r\n|"
		"|EXE_HTTPManager::_Run_10|applying a patch|"
		"|EXE_HTTPManager::CheckPatchPac_1|Check Patch|"
		"|EXE_HTTPManager::UpdatePatchFile_1|Start Pac Patch|"
		"|EXE_HTTPManager::UpdatePatchFile_2|Download Pac[%1/%2]|"
		"|EXE_HTTPManager::UpdatePatchFile_3|Check Pac[%1/%2]|"
		"|EXE_HTTPManager::UpdatePatchFile_4|Update Pac[%1/%2]|"
		"|EXE_HTTPManager::UpdatePatchFile_5|Pac Patch Complate|"
		"|EXE_HTTPManager::DeleteGarbage_1| applying a patch [%1%%/%2%%]|"
		"|EXE_HTTPManager::_RunAdmin_1|Error extracting the package file number %1.\r\n\r\n%2|"
		"|EXE_HTTPManager::_RunAdmin_2|Completed.|"
		"|EXE_HTTPManager::_RunAdmin_3|Error copying folder(s).\r\n\r\n|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_1|Original folder.|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_2|Destination folder.|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_3|Copying folder(s).|"
		"|EXE_HTTPManager::_RunOptionCopyFolder_4|Completed.|"
		"|EXE_HTTPManager::AddPacFile_1|Merging: #%1 file.|"
		"|EXE_HTTPManager::AddPacFile_2|Error merging files: %1.|"
		"|EXE_HTTPManager::AddPacFile_3|Failed to merge files.\r\nFile name: %1\r\nFile name in the package file: %2\r\nPackage file array: %3 , File CRC: %4, GetLastErrorValue: %5, Exception: %6, |"
		"|EXE_HTTPManager::AddPacFile_4|Failed to delete downloaded files while merging files.\r\nFile name: %1\r\nGetLastError:%2, |"
		"|EXE_HTTPManager::CheckPac_1|Error checking package is NULL.|"
		"|EXE_HTTPManager::CheckPac_2|The package parameter for checking is NULL.\r\nGetLastError: %1\r\n|"
		"|EXE_HTTPManager::CheckPac_3|Verifying %1/%2 files: File [%3%%].|"
		"|EXE_HTTPManager::CopyVersionupFiles_1|Processing manual patching: [%1%%].|"
		"|EXE_HTTPManager::CreateAllNewPacFile_1|Failed optimizing #%1 file.\r\n Please run the program again.\r\n(error code: 212)\r\n\r\n%2|"
		"|EXE_HTTPManager::CreateNewPacFile_1|Failed to delete old files to create a new package file.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::CreateNewPacFile_2|Error saving the new package.|"
		"|EXE_HTTPManager::CreateNewPacFile_3|Failed to create and open a new package file.\r\n|"
		"|EXE_HTTPManager::CreateNewPacFile_4|Error: The new package is NULL.|"
		"|EXE_HTTPManager::CreateNewPacFile_5|The iop file parameter for the new package is NULL.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::CreateNewPacFile_6|Error opening a new package.|"
		"|EXE_HTTPManager::CreateNewPacFile_7|Failed to open the iop file for a new package.\r\nFile name: %1\r\nGetLastError: %2,Exception: %3|"
		"|EXE_HTTPManager::CreateNewPacFile_8|New package information error.|"
		"|EXE_HTTPManager::CreateNewPacFile_9|Failed to initialize the file information of the iop file for a new package.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::CreateNewPacFile_10|New package NULL 2 error.|"
		"|EXE_HTTPManager::CreateNewPacFile_11|The new iop parameter value is NULL.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::CreateNewPacFile_12|Error opening the new package 2.|"
		"|EXE_HTTPManager::CreateNewPacFile_13|Failed to open the new iop file.\r\nFile name: %1\r\nGetLastError: %2, File CRC: %3, Exception: %4|"
		"|EXE_HTTPManager::CreateNewPacFile_14|Optimizing:%1/%2 files [%3%%].|"
		"|EXE_HTTPManager::CreateNewPacFile_15|New package information error.|"
		"|EXE_HTTPManager::CreateNewPacFile_16|Failed to read the old iop file information to create a new package .\r\nFile name: %1\r\nGetLastError: %2,Array: %3,Exception: %4|"
		"|EXE_HTTPManager::CreateNewPacFile_17|New package file data error.|"
		"|EXE_HTTPManager::CreateNewPacFile_18|Failed to read the old iop file data to create a new package.\r\nFile name: %1\r\nFile hash: %2,File index: %3,Compressed file size: %4,File size: %5,GetLastError: %6,Array: %7,Exception: %8|"
		"|EXE_HTTPManager::CreateNewPacFile_19|New package file merging error.|"
		"|EXE_HTTPManager::CreateNewPacFile_20|Failed to merge files into a new rs.iop.\r\nFile name: %1\r\n????: %2,File index: %3,Compressed file size: %4,File size: %5,GetLastError: %6,Array: %7,Exception: %8|"
		"|EXE_HTTPManager::CreateNewPacFile_21|New package size error.|"
		"|EXE_HTTPManager::CreateNewPacFile_22|The size of the old iop file for creating a new package is 0.\r\nFile name: %1\r\nFile hash: %2,File index: %3,Compressed file size: %4,File size: %5,GetLastError: %6,Array: %7,Exception: %8|"
		"|EXE_HTTPManager::CreateNewPacFile_23|Error copying the new package.|"
		"|EXE_HTTPManager::CreateNewPacFile_24|Failed to copy the new iop.\r\nFile name: %1\r\nNewFile name: %2\r\nGetLastError: %3|"
		"|EXE_HTTPManager::CreateNewPacFile_25|Error deleting the new package.|"
		"|EXE_HTTPManager::CreateNewPacFile_26|Failed to delete the original file after completing copy.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::DownLoadProcess_1|Downloading #%1 file.|"
		"|EXE_HTTPManager::DownLoadProcess_2|OpenUrl error: %1.|"
		"|EXE_HTTPManager::DownLoadProcess_3|OpenURL failed.\r\nFile name: %1\r\nError: %2|"
		"|EXE_HTTPManager::DownLoadProcess_4|Error OpenUrl NULL: %1.|"
		"|EXE_HTTPManager::DownLoadProcess_5|The CInternetFile value is NULL.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::DownLoadProcess_6|Failed to delete the old files while downloading.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::DownLoadProcess_7|Error opening file: %1.|"
		"|EXE_HTTPManager::DownLoadProcess_8|Failed to open files to save.\r\n|"
		"|EXE_HTTPManager::DownLoadProcess_9|Downloading %1 file[%2%%].|"
		"|EXE_HTTPManager::DownLoadProcess_10|Error writing file: %1.|"
		"|EXE_HTTPManager::DownLoadProcess_11|Failed to write files to save.\r\n|"
		"|EXE_HTTPManager::DownLoadProcess_12|Error receiving file: %1.|"
		"|EXE_HTTPManager::DownLoadProcess_13|Failed to receive files to save.\r\n|"
		"|EXE_HTTPManager::DownLoadProcess_14|Error receiving Range HttpServer Request.|"
		"|EXE_HTTPManager::FileCopy_1|Error copying file: %1.|"
		"|EXE_HTTPManager::FileCopy_2|Failed to copy files.\r\nFile name: %1\r\nNew file name: %2\r\nGetLastError: %3, |"
		"|EXE_HTTPManager::GetUpdateFile_1|Verifying downloads.|"
		"|EXE_HTTPManager::GetUpdateFile_2|Verifying updates [%1%%].|"
		"|EXE_HTTPManager::InitPac_1|Failed to assign memory to the package library.\r\n Please run the program again.\r\n(error code: 213)\r\n\r\nArray: %1, GetLastError: %2|"
		"|EXE_HTTPManager::OpenAllBigPacForGarbageSize_1|Failed to open #%1 iop.\r\nFile name: %2, GetLastError: %3\r\nPlease run the program again.\r\n(error code: 225)\r\n\r\n|"
		"|EXE_HTTPManager::ParseDeleteFileList_1|Parsing files to delete.|"
		"|EXE_HTTPManager::ParsePatchFile_1|Failed to open files to parse.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::ParsePatchFile_2|Failed to delete the old files after parsing.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::ProcessCheckPac_1|Problem in client files.\r\n\r\nPress [Yes] to run a complete diagnosis \r\n\r\nand download the client if errors are found.|"
		"|EXE_HTTPManager::ProcessCheckPac_2|Errors found in client files.\r\n\r\nDownload the client again.|"
		"|EXE_HTTPManager::ProcessCheckPac_3|Failed to open #%1 iop.\r\nFailed to delete the file.\r\nFile name: %2, GetLastError: %3\r\nPlease run the program again.\r\n(error code: 224)\r\n\r\n|"
		"|EXE_HTTPManager::ProcessNewPacFile_1|Already optimized.|"
		"|EXE_HTTPManager::ProcessNewPacFile_2|Already optimized.|"
		"|EXE_HTTPManager::Run_1|An exception occurred in the main loop.\r\n Please run the program again.\r\n(error code: 209)\r\n\r\n|"
		"|EXE_HTTPManager::SetTextWaitNewPac_1|Verifying optimization.[%1]|"
		"|EXE_HTTPManager::SetupFull_1|Error extracting #%1 package.\r\n\r\n%2|"
		"|EXE_HTTPManager::SetupFull_2|Failed to delete the installed file version information.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::SetupFull_3|Failed to open the installed version information file.\r\n|"
		"|EXE_HTTPManager::SetupFull_4|Error opening the package file.|"
		"|EXE_HTTPManager::SetupFull_5|Failed to open #%1 iop file after the installation.\r\nFile name: %2\r\nGetLastError: %3, File CRC: %4, Exception: %5, |"
		"|EXE_HTTPManager::StartGame_1|The game is running.|"
		"|EXE_HTTPManager::StartGame_2|The login key has expired.\r\n\r\n         Please log in again\r\n\r\n            for safety.|"
		"|EXE_HTTPManager::StartGame_3|The game will be started automatically.[%1]|"
		"|EXE_HTTPManager::StartGame_4|Press the Start button to start the game.|"
		"|EXE_HTTPManager::StartGame_5|Web Broker Version is low. Please restart the game.|"
		"|EXE_HTTPManager::StartGame_6|Web Broker Error!!|"
		"|EXE_HTTPManager::UnFull_1|Error: Full installation is NULL.|"
		"|EXE_HTTPManager::UnFull_2|The package variable to be used by the installation version is NULL.\r\nGetLastError: %1, |"
		"|EXE_HTTPManager::UnFull_3|Error opening the full installation.|"
		"|EXE_HTTPManager::UnFull_4|Failed to open the full installation.\r\nFile name: %1\r\nGetLastError: %2, File CRC: %3, Exception: %4, |"
		"|EXE_HTTPManager::UnFull_5|Information error: Full installation.|"
		"|EXE_HTTPManager::UnFull_6|Failed to read the installation information.\r\nFile name: %1\r\nGetLastError: %2, File CRC: %3, File array: %4, Exception: %5, |"
		"|EXE_HTTPManager::UnFull_7|Extracting #%1 file[%2%%].|"
		"|EXE_HTTPManager::UnFull_8|Failed to delete the older version files.\r\nFile name: %1\r\nGetLastError: %2, |"
		"|EXE_HTTPManager::UnFull_9|Error extracting the full installation: %1.|"
		"|EXE_HTTPManager::UnFull_10|Failed to extract the full installation file.\r\nFile name: %1\r\nGetLastError: %2, Installation file CRC: %3, Array: %4, Exception: %5, |"
		"|EXE_HTTPManager::UnFull_11|Failed to delete the installed version.\r\nFile name: %1\r\nGetLastError: %2, |"
		"|EXE_HTTPManager::UnPac_1|Error: Full package is NULL.|"
		"|EXE_HTTPManager::UnPac_2|The rs.iop file variable used to extract package files is NULL.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::UnPac_3|Error opening the full package.|"
		"|EXE_HTTPManager::UnPac_4|Failed to open the rs.iop file used to extract package files.\r\nFile name: %1\r\nGetLastError: %2,Exception: %3|"
		"|EXE_HTTPManager::UnPac_5|Full package INIT error.|"
		"|EXE_HTTPManager::UnPac_6|Failed to initialize the rs.iop file to extract package files.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::UnPac_7|Full package information error.|"
		"|EXE_HTTPManager::UnPac_8|Failed to read the old rs.iop file information to extract package files.\r\nFile name: %1\r\nGetLastError: %2,Array: %3,Exception: %4|"
		"|EXE_HTTPManager::UnPac_9|Extracting IOP: %1/%2 file [%3%%].|"
		"|EXE_HTTPManager::UnPac_10|Error deleting the old file to extract package files.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::UnPac_11|Error extracting the full package.|"
		"|EXE_HTTPManager::UnPac_12|Failed to extract files to extract package files.\r\nFile name: %1\r\nFile hash: %2,File index: %3,Compressed file size: %4,GetLastError: %5,Array: %6,Exception: %7|"
		"|EXE_HTTPManager::UnPacPieceFile_1|Extracting #%1 file.|"
		"|EXE_HTTPManager::UnPacPieceFile_2|Failed to delete old files during individual extraction.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::UnPacPieceFile_3|Failed to find the files to extract during individual extraction.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::UnPacPieceFile_4|Error extracting individual file: %1.|"
		"|EXE_HTTPManager::UnPacPieceFile_5|Failed to extract individual files.\r\nFile name: %1\r\nError return value: %2, File CRC: %3, GetLastError: %4, Exception: %5|"
		"|EXE_HTTPManager::UnPacPieceFile_6|Failed to delete downloaded files during individual extraction.\r\nFile name: %1\r\nGetLastError: %2|"
		"|EXE_HTTPManager::UpdateFileLoop_1|Parsing files to download.|"
		"|EXE_HTTPManager::UpdateFileLoop_2|Retrying due to error: %1/%2.|"
		"|EXE_HTTPManager::UpdateOneFile_1|An error occurred while downloading files.\r\nThe program will retry downloading (max. 100 times)\r\nClick the X button\r\nto close the program.\r\n(error code: 218)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_2|Error: Downloaded file corruption: %1.|"
		"|EXE_HTTPManager::UpdateOneFile_3|The downloaded file is damaged.\r\nThe patch server might be busy.\r\nThe program will retry downloading the file. (max. 100 times)\r\nClick the X button\r\nto close the program.\r\n(error code: 216)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_4|Downloaded file size error.|"
		"|EXE_HTTPManager::UpdateOneFile_5|Invalid file size.\r\nFile name: %1\r\nServer file size: %2, Downloaded file size: %3, Server file CRC: %4, Downloaded file CRC: %5|"
		"|EXE_HTTPManager::UpdateOneFile_6|The size of the downloaded file has been changed.\r\nThe patch information file maybe not up-to-date or\r\ninfected by virus.\r\nIf the problem persists, try the followings:\r\n\r\n1. Delete the [Lost Saga] installation folder.\r\n   For Internet Explorer 7 users, Tools -> Internet options -> General -> Delete -> Delete all-> Select [Delete files and settings stored by add-ons.] -> Yes\r\n   For Internet Explorer 6 users, Tools -> Internet options -> General -> Delete Cookies ->  Delete\r\n                                   Tools -> Internet options -> General -> Delete Files -> Select [Delete all offline content] ->|"
		"|EXE_HTTPManager::UpdateOneFile_7|Sever file size: %1, Downloaded file size: %2, Server file CRC: %3|"
		"|EXE_HTTPManager::UpdateOneFile_8|An error occurred while merging files.\r\nThe program will retry merging. (max. 100 times)\r\nClick the X button\r\nto close the program.\r\n(error code: 219)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_9|Server file size: %1, Downloaded file size: %2, Server file CRC: %3|"
		"|EXE_HTTPManager::UpdateOneFile_10|An error occurred during individual file extraction.\r\nThe program will retry extracting. (max. 100 times)\r\nClick the X button\r\nto close the program.\r\n(error code: 220)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_11|Server file size: %1, Downloaded file size: %2, Server file CRC: %3|"
		"|EXE_HTTPManager::UpdateOneFile_12|An error occurred while copying files.\r\nThe program will retry copying. (max. 100 times)\r\nClick the X button\r\nto close the program.\r\n(error code: 221)\r\n\r\n|"
		"|EXE_HTTPManager::UpdateOneFile_13|Server file size: %1, Downloaded file size: %2|"
		"|EXE_HTTPManager::UpdateOneFile_14|Failed to install the full version.\r\nThe program will retry installing. (max. 100 times)\r\nClick the X button\r\nto close the program.\r\n(error code: 217)\r\n\r\n|"
		"|EXE_ioErrorDlg::ShowErrorDlg_1|Ver : %1\r\n--- System Requirements ---\r\n%2\r\n\r\n--- Error Information ---\r\n%3|"
		"|EXE_ioLoginDlg::FirstConnectServer_1|Connecting to the %1 server.|"
		"|EXE_ioLoginDlg::OnTimer_1|%1 server not responding, connecting to the %2 server.|"
		"|EXE_ioLoginDlg::OnTimer_2|%1 server not responding, connecting to the %2 server.|"
		"|EXE_ioLoginDlg::SendServer_1|The login request is sent to the %1 server, waiting for response.|"
		"|EXE_ioLoginDlg::SetTextNetworkConnected_1|Connected to the %1 server.|";
/*
	return 	"|EXE_CAutoUpgradeApp::IsDuplication_1|\r\n\r\n      [lostsaga] กำลั?Runอยู่\r\n\r\n      ปิ?[lostsaga] แล้วลอ?Run ใหม่อีกครั้ง\r\n\r\n\r\n      (Error Num:201)|"
			"|EXE_CAutoUpgradeDlg::OnCopyData_1|กำลังเชื่อมต่อ game server|"
			"|EXE_CAutoUpgradeDlg::OnCopyData_2|กำลังเชื่อมต่อ UDP|"	
			"|EXE_CAutoUpgradeDlg::OnCopyData_3|การเชื่อมต่อ Game Server ล้มเหล?"
			"|EXE_CAutoUpgradeDlg::OnTimer_1|กำลั?Run Game|"
			"|EXE_CAutoUpgradeDlg::OnTimer_2|ใช้เวล?0นาที ในกา?Run game ซึ่งล้มเหลวแล้?r\n(Error Num:210)|"
			"|EXE_CAutoUpgradeDlg::OnTimer_3|การเชื่อมต่อ game server ล้มเหล?"
			"|EXE_CAutoUpgradeDlg::OnTimer_4|กำลังตรวจสอบ optimization |"	
			"|EXE_CAutoUpgradeDlg::OnTimer_5|กำลังตรวจสอบ optimization |"
			"|EXE_CAutoUpgradeDlg::OnTimer_6|เกมเริ่มอัตโนมัต?"			
			"|EXE_CAutoUpgradeDlg::OnTimer_7|เกมเริ่มอัตโนมัต?"			
			"|EXE_CAutoUpgradeDlg::OnTimer_8|กา?Run Client ล้มเหล?r\n(Error Num:226)|"
			"|EXE_CAutoUpgradeDlg::OnTimer_9|กา?Run Client ล้มเหล?"
			"|EXE_CAutoUpgradeDlg::SetWantEndDialog_1|กำลังปิดตั?กรุณารอสักครู่|"
			"|EXE_Help::CheckRightHDDSpace_1|เพื่อการ updaete lostsaga นั้น \r\n ต้องการที่ว่างใน Harddisk %1 MB ขึ้นไป\r\n(Error Num:207)\r\n\r\nTotal size:%2M, Free space:%3M, พื้นที่ที่lostsagaต้องกา?%4M|"			
			"|EXE_Help::CheckDownloadedFile_1|การเปิดไฟล์เพื่อการตรวจสอบ integrity ล้มเหลวแล้?r\n|"
			"|EXE_Help::CheckDownloadedFile_2|ไฟล์ที?Downloadมา เป็น error webpage\r\nชื่อไฟล์ :%1\r\nไฟล์CRC:%2, ขนาดไฟล์:%3,GetLastError:%4|"			
			"|EXE_HTTPManager::_Run_1|กำลังอ่า?Local Data Patch|"
			"|EXE_HTTPManager::_Run_2|เวอร์ชั่นของ DirectX ที่ลงไว้เป็นเวอร์ชั่นเก่?r\nกรุณาล?DirectX เวอร์ชั่นล่าสุ?r\ndriver ขอ?Graphics card เป็นเวอร์ชั่นล่าสุดหรือไม่นั้น กรุณาตรวจสอบด้วย\r\n(Error Num:211)|"
			"|EXE_HTTPManager::_Run_3|เปิด iop ที?%1 ล้มเหล?\r\nการลบไฟล์ล้มเหลว\r\nชื่อไฟล์:%2, GetLastError:%3\r\nกรุณ?Run Program ใหม่อีกครั้ง\r\n(Error Num:222)\r\n\r\n|"			
			"|EXE_HTTPManager::_Run_4|การdownloadไฟล์?อมูลล้มเหล?r\nPatch Server อาจหนาแน่นได?r\nกรุณ?Run Program ใหม่ในภายหลั?r\n(Error Num:203)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_5|ไฟล์?อมูลเสีย\r\nPatch Server อาจหนาแน่นได?r\nกรุณ?Run Program ใหม่ในภายหลั?r\n(Error Num:215)\r\n\r\n|	"
			"|EXE_HTTPManager::_Run_6|ไม่สามารถคลา?pack ไฟล์?อมูลได?r\n กรุณาตรวจสอบว่าการ Sync ไฟล์ patch มีปั?าหรือไม่\r\n แล้ว Run Program ใหม่อีกครั้ง\r\n(Error Num:204)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_7|กา?analyze ไฟล์?อมูลล้มเหล?r\n กรุณ?Run Program ใหม่อีกครั้ง\r\n(Error Num:205)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_8|การตรวจสอบพื้นที่ว่างใ?Harddisk ล้มเหล?r\nดำเนินการอย่างระมัดระวัง\r\nว่ามีพื้นที่ว่าง Harddisk เพียงพ?r\nหากปัญหาเกิดขึ้นอย่างต่อเนื่อง กรุณาเคลียร์พื้นที่ว่างใ?Harddisk ด้วย\r\n(Error Num:223)\r\n\r\nGetLastError:%1|	"
			"|EXE_HTTPManager::_Run_9|กา?download ไฟล์แล?renew ไฟล์ล้มเหล?(พยายาม 100 ครั้?ล้มเหล?.\r\nกรุณ?Run Program ใหม่อีกครั้ง\r\nหากปัญหาเกิดขึ้นต่อเนื่อ?ที่รายการเมนูโปรแกรม\r\n remove lostsaga แล้ว scan virus ด้วย\r\nหรือ ตรวจสอบสถานะ Internet ด้วย\r\n(Error Num:206)\r\n\r\n|"
			"|EXE_HTTPManager::_Run_10|applying a patch|"
			"|EXE_HTTPManager::DeleteGarbage_1| applying a patch [%1/%2]|"
			"|EXE_HTTPManager::_RunAdmin_1|เกิด error ในระหว่างการคลาย pack ไฟล์ %1\r\n\r\n%2|"
			"|EXE_HTTPManager::_RunAdmin_2|เสร็จเรียบร้อยแล้ว|"
			"|EXE_HTTPManager::_RunAdmin_3|เกิด error ในขณ?Copy Floder\r\n\r\n|"
			"|EXE_HTTPManager::_RunOptionCopyFolder_1|error Folder ต้นฉบั?"		
			"|EXE_HTTPManager::_RunOptionCopyFolder_2|error Folder ปลายทา?"			
			"|EXE_HTTPManager::_RunOptionCopyFolder_3|กำลั?Copy Folder|"	
			"|EXE_HTTPManager::_RunOptionCopyFolder_4|เสร็จเรียบร้อยแล้ว|"	
			"|EXE_HTTPManager::AddPacFile_1|กำลังรวม:ไฟล์ที?%1|"
			"|EXE_HTTPManager::AddPacFile_2|การรวม error file:%1.|"
			"|EXE_HTTPManager::AddPacFile_3|การรวมไฟล์ล้มเหล?r\nชื่อไฟล์:%1\r\nในไฟล์ pack ชื่อไฟล์:%2\r\npack file array :%3 , ไฟล์ CRC:%4, ค่?GetLastError:%5, Exception:%6, |"			
			"|EXE_HTTPManager::AddPacFile_4|กำลังรวมไฟล์ การลบไฟล์ที่ดาวโหลดมาล้มเหลวแล้ว\r\nชื่อไฟล์:%1\r\nGetLastError:%2, |"			
			"|EXE_HTTPManager::CheckPac_1|error check pack NULL.|"
			"|EXE_HTTPManager::CheckPac_2| ตัวแปรที่ใช้งานในการ check คื?NULL\r\nGetLastError:%1\r\n|"
			"|EXE_HTTPManager::CheckPac_3|กำลังตรวจสอบไฟล์ :ไฟล์ที?%1/%2[%3%%].|"
			"|EXE_HTTPManager::CopyVersionupFiles_1|manual patch:[%1%%].|"
			"|EXE_HTTPManager::CreateAllNewPacFile_1|กา?optimization ไฟล์ที?%1 ล้มเหล?r\n กรุณ?Run Program ใหม่อีกครั้ง\r\n(Error Num:212)\r\n\r\n%2|"
			"|EXE_HTTPManager::CreateNewPacFile_1|การลบไฟล์ที่ย้ายมาเพื่อการทำไฟล์ pack ใหม่ล้มเหล?\r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::CreateNewPacFile_2|error save new pack.|"			
			"|EXE_HTTPManager::CreateNewPacFile_3|การเปิดการสร้า?pack file ใหม่ล้มเหล?r\n|"			
			"|EXE_HTTPManager::CreateNewPacFile_4|error new pack NULL.|"			
			"|EXE_HTTPManager::CreateNewPacFile_5|ตัวแปรไฟล์ iop สำหรับการสร้างไฟล์ pack ใหม่คื?NULL \r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::CreateNewPacFile_6|error open new pack.|"			
			"|EXE_HTTPManager::CreateNewPacFile_7|การเปิดไฟล?iop สำหรับการสร้างไฟล์ pack ใหม่ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2,Exception:%3|"			
			"|EXE_HTTPManager::CreateNewPacFile_8|?อมูล error new pack|"			
			"|EXE_HTTPManager::CreateNewPacFile_9|กา?reset?อมูลไฟล์ iop สำหรับการสร้างไฟล์ pack ใหม่ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::CreateNewPacFile_10|error new pack NULL 2.|"			
			"|EXE_HTTPManager::CreateNewPacFile_11|ตัวแปร iop ที่สร้างใหม่คื?NULL \r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::CreateNewPacFile_12|error open new pack2.|"			
			"|EXE_HTTPManager::CreateNewPacFile_13|การเปิดไฟล?iop ที่สร้างใหม่ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2, ไฟล์CRC:%3, Exception:%4|"			
			"|EXE_HTTPManager::CreateNewPacFile_14|กำลั?Optimization :ไฟล์ที?%1/%2[%3%%].|"			
			"|EXE_HTTPManager::CreateNewPacFile_15|?อมูล error new pack file|"			
			"|EXE_HTTPManager::CreateNewPacFile_16|การอ่านข้อมู?iop ที่ย้ายม?สำหรับการสร้างไฟล์ pack ใหม่ ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2,Array:%3,Exception:%4|"			
			"|EXE_HTTPManager::CreateNewPacFile_17|error new pack file data|"			
			"|EXE_HTTPManager::CreateNewPacFile_18|การอ่า?data file iop ที่ย้ายม?สำหรับการสร้างไฟล์ pack ใหม่ ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nFile Hash:%2,File Index:%3,ขนาดไฟล์ zip:%4,ขนาดไฟล์:%5,GetLastError:%6,Array:%7,Exception:%8|"			
			"|EXE_HTTPManager::CreateNewPacFile_19|การรวม error new pack file|"			
			"|EXE_HTTPManager::CreateNewPacFile_20|การรวม file ที?rs.iop ใหม่ ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nFile Hash:%2,File Index:%3,ขนาดไฟล์ zip:%4,ขนาดไฟล์:%5,GetLastError:%6,Array:%7,Exception:%8|"			
			"|EXE_HTTPManager::CreateNewPacFile_21|error new pack size|"			
			"|EXE_HTTPManager::CreateNewPacFile_22|iop file Data size ที่ย้ายมาสำหรับการสร้างไฟล?pack ใหม่ คื?0 \r\nชื่อไฟล์:%1\r\nFile Hash:%2,File Index:%3,ขนาดไฟล์ zip:%4,ขนาดไฟล์:%5,GetLastError:%6,Array:%7,Exception:%8|"			
			"|EXE_HTTPManager::CreateNewPacFile_23|copy error new pack|"			
			"|EXE_HTTPManager::CreateNewPacFile_24|กา?copy iop ใหม่ ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nชื่อไฟล์ใหม่:%2\r\nGetLastError:%3|"			
			"|EXE_HTTPManager::CreateNewPacFile_25|ลบ error new pack|"			
			"|EXE_HTTPManager::CreateNewPacFile_26|หลังจา?copy new file แล้ว ลบ new file ที?copy มาล้มเหล?\r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::DownLoadProcess_1|กำลั?download:ไฟล์ที?%1|"			
			"|EXE_HTTPManager::DownLoadProcess_2|error OpenUrl:%1.|"			
			"|EXE_HTTPManager::DownLoadProcess_3|OpenURL ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nerror:%2|"			
			"|EXE_HTTPManager::DownLoadProcess_4|error OpenUrl NULL:%1.|"			
			"|EXE_HTTPManager::DownLoadProcess_5|ค่?CInternetFile คื?NULL\r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::DownLoadProcess_6|ในระหว่างการ download file ลบไฟล์ที่ย้ายมาล้มเหลว\r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::DownLoadProcess_7|error file open:%1.|"			
			"|EXE_HTTPManager::DownLoadProcess_8|การเปิดไฟล์สำหรับการบันทึกไฟล์ล้มเหลวแล้?r\n|	"		
			"|EXE_HTTPManager::DownLoadProcess_9|กำลังdownload:ไฟล์ที?%1[%2%%].|"			
			"|EXE_HTTPManager::DownLoadProcess_10|เขีย?error file:%1.|"			
			"|EXE_HTTPManager::DownLoadProcess_11|การเขียนไฟล์สำหรับการบันทึกไฟล์ล้มเหลวแล้ว\r\n|"			
			"|EXE_HTTPManager::DownLoadProcess_12|รั?error file:%1.|"			
			"|EXE_HTTPManager::DownLoadProcess_13|การรับไฟล์สำหรับการบันทึกไฟล์ล้มเหลวแล้ว\r\n|"			
			"|EXE_HTTPManager::FileCopy_1|copy error file:%1.|"			
			"|EXE_HTTPManager::FileCopy_2|กา?copy file ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nชื่อไฟล์ใหม่:%2\r\nGetLastError:%3, |"			
			"|EXE_HTTPManager::GetUpdateFile_1|กำลังตรวจสอบกา?download|"			
			"|EXE_HTTPManager::GetUpdateFile_2|กำลังตรวจสอบกา?update [%1%%].|"			
			"|EXE_HTTPManager::InitPac_1|กา?assign Pack Library memory ล้มเหลวแล้?r\n กรุณ?Run Program ใหม่อีกครั้ง\r\n(Error Num:213)\r\n\r\nArray:%1, GetLastError:%2|"			
			"|EXE_HTTPManager::OpenAllBigPacForGarbageSize_1|การเปิ?iop ที?%1 ล้มเหลวแล้?r\nชื่อไฟล์:%2, GetLastError:%3\r\nกรุณ?Run Program ใหม่อีกครั้ง\r\n(Error Num:225)\r\n\r\n|"			
			"|EXE_HTTPManager::ParseDeleteFileList_1|กำลั?analyze file ที่ล?"			
			"|EXE_HTTPManager::ParsePatchFile_1|การเปิดไฟล์เพื่อกา?parsing ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::ParsePatchFile_2|การลบไฟล์ที่ย้ายมาหลัง parsing ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::ProcessCheckPac_1|พบปั?าจากไฟล์ Client \r\n\r\nหากก?Yes]จะทำการตรวจสอบไฟล์ทั้งหม?r\n\r\nหากเกิ?error กรุณ?download client ใหม่อีกครั้ง|"			
			"|EXE_HTTPManager::ProcessCheckPac_2|พบ Error จากไฟล?Client\r\n\r\nกรุณ?download client ใหม่อีกครั้ง|"			
			"|EXE_HTTPManager::ProcessCheckPac_3|การเปิดไฟล?iop ที?1ล้มเหล?แล?r\n การลบไฟล?ล้มเหลวแล้?r\nชื่อไฟล์:%2, GetLastError:%3\r\nกรุณ?Run Program ใหม่อีกครั้ง\r\n(Error Num:224)\r\n\r\n|"			
			"|EXE_HTTPManager::ProcessNewPacFile_1|Optimization ไปแล้ว|"			
			"|EXE_HTTPManager::ProcessNewPacFile_2|Optimization ไปแล้ว|"			
			"|EXE_HTTPManager::Run_1|เกิด error ที่ยกเว้นไว้ ใน main loop\r\n กรุณ?Run Program ใหม่อีกครั้ง\r\n(Error Num:209)\r\n\r\n|"			
			"|EXE_HTTPManager::SetTextWaitNewPac_1|กำลังตรวจสอบกา?optimization [%1]|"			
			"|EXE_HTTPManager::SetupFull_1|เกิก error ในขณะคลา?pack file %1\r\n\r\n%2|"			
			"|EXE_HTTPManager::SetupFull_2|การลบข้อมู?version install version ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::SetupFull_3|การเปิ??อมูล version install version file ล้มเหลวแล้?r\n|"			
			"|EXE_HTTPManager::SetupFull_4|open error pack file|"			
			"|EXE_HTTPManager::SetupFull_5|การเปิดไฟล?iop ที? %1 หลังกา?Install ล้มเหลวแล้?r\nชื่อไฟล์:%2\r\nGetLastError:%3, fileCRC:%4, Exception:%5, |"			
			"|EXE_HTTPManager::StartGame_1|กำลั?Run Game|"			
			"|EXE_HTTPManager::StartGame_2|กวลาการใช้งานของ Login key หมดลงแล้?r\n\r\n         เพื่อการ Login อย่างปลอดภัย\r\n\r\n            กรุณ?login ใหม่อีกครั้ง|"			
			"|EXE_HTTPManager::StartGame_3|เกมเริ่มอัตโนมัต?%1]|"			
			"|EXE_HTTPManager::StartGame_4|คลิกที?Start Game เพื่อเริ่มเก?Lost Saga|"
			"|EXE_HTTPManager::StartGame_5|Web Broker Version is low. Please restart the game.|"
			"|EXE_HTTPManager::StartGame_6|Web Broker Error!!|"
			"|EXE_HTTPManager::UnFull_1|error full install NULL.|"			
			"|EXE_HTTPManager::UnFull_2|install version นั้น ตัวแปร pack ที่จะใช้งานคือ NULL\r\nGetLastError:%1, |"			
			"|EXE_HTTPManager::UnFull_3|open error full install|"			
			"|EXE_HTTPManager::UnFull_4|การเปิ?install version ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2, fileCRC:%3, Exception:%4, |"			
			"|EXE_HTTPManager::UnFull_5|?อมูล error full install|"			
			"|EXE_HTTPManager::UnFull_6|การอ่านข้อมู?install ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2, fileCRC:%3, fileArray:%4, Exception:%5, |"			
			"|EXE_HTTPManager::UnFull_7|กำลังคลา?zip:ไฟล์ที?%1[%2%%].|"			
			"|EXE_HTTPManager::UnFull_8|การลบไฟล์ที่ย้ายมาขอ?install version ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2, |"			
			"|EXE_HTTPManager::UnFull_9|คลาย zip error full install :%1.|"			
			"|EXE_HTTPManager::UnFull_10|การคลา?zip install version ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2, install fileCRC:%3, Array:%4, Exception:%5, |"			
			"|EXE_HTTPManager::UnFull_11|ลบ install version ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2, |"			
			"|EXE_HTTPManager::UnPac_1|error full pack NULL.|"			
			"|EXE_HTTPManager::UnPac_2|ตัวแปร rs.iopfile สำหรับการคลา?pack file คื?NULL\r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::UnPac_3|open error full pack |"			
			"|EXE_HTTPManager::UnPac_4|การเปิ?rs.iopfile สำหรับคลาย pack file ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2,Exception:%3|"			
			"|EXE_HTTPManager::UnPac_5|error full pack INIT.|"			
			"|EXE_HTTPManager::UnPac_6|กา?reset ?อมูลไฟล์ rs.iop สำหรับคลาย pack file ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::UnPac_7|?อมูล error full pack |	"		
			"|EXE_HTTPManager::UnPac_8|การอ่านข้อมูลไฟล? rs.iop ที่ย้ายม?สำหรับคลาย pack file ล้มเหลวแล้?\r\nชื่อไฟล์:%1\r\nGetLastError:%2,Array:%3,Exception:%4|"			
			"|EXE_HTTPManager::UnPac_9|กำลังคลา?IOP:ไฟล์ที?%1/%2[%3%%].|"			
			"|EXE_HTTPManager::UnPac_10|การลบไฟล์ที่ย้ายมา สำหรับคลาย pack file ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::UnPac_11|การคลา?zip error full pack|"			
			"|EXE_HTTPManager::UnPac_12|การคลา?zip file สำหรับการคลา?pack file ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nFile Hash:%2,File Index:%3,ขนาดไฟล์ zip:%4,GetLastError:%5,Array:%6,Exception:%7|"			
			"|EXE_HTTPManager::UnPacPieceFile_1|กำลังคลา?zip:ไฟล์ที?%1|"			
			"|EXE_HTTPManager::UnPacPieceFile_2|การลบไฟล์ที่ย้ายมาจากการคลาย zip ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::UnPacPieceFile_3|ไฟล์คลาย zip จากการคลาย zip ไม่มีอยู?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::UnPacPieceFile_4|error unpack:%1.|"			
			"|EXE_HTTPManager::UnPacPieceFile_5|การคลา?zip ไฟล์ ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nerror ค่?eturn:%2, ค่?fileCRC:%3, ค่?etLastError:%4, Exception:%5|"			
			"|EXE_HTTPManager::UnPacPieceFile_6|ลบไฟล์ที่ดาวโหลดจากการคลาย zip ล้มเหลวแล้?r\nชื่อไฟล์:%1\r\nGetLastError:%2|"			
			"|EXE_HTTPManager::UpdateFileLoop_1|กำลั?analyze ไฟล์เป้าหมาย download |"			
			"|EXE_HTTPManager::UpdateFileLoop_2|กำลังทดลองใหม่เนื่องจากเกิ?error:%1/%2.|"			
			"|EXE_HTTPManager::UpdateOneFile_1|เกิด error ในการดาวโหลดไฟล์\r\nเริ่มการทดลองใหม่อัตโนมัติ(รว?00ครั้?\r\nหากต้องการปิดโปรแกรม\r\nกรุณาคลิกที่ปุ่ม X ของการอัพเดทอัตโนมัต?r\n(Error Num:218)\r\n\r\n|"			
			"|EXE_HTTPManager::UpdateOneFile_2|error download file เสียหา?%1.|"			
			"|EXE_HTTPManager::UpdateOneFile_3|file ที่ถูก download เสียหา?r\nPatch Server อาจหนาแน่นได?r\nเริ่มการทดลองใหม่อัตโนมัติ(รว?00ครั้?\r\nหากต้องการปิดโปรแกรม\r\nกรุณาคลิกที่ปุ่ม X ของการอัพเดทอัตโนมัต?r\n(Error Num:216)\r\n\r\n|"			
			"|EXE_HTTPManager::UpdateOneFile_4|error download ปั?าขนาดไฟล?"			
			"|EXE_HTTPManager::UpdateOneFile_5|ขนาดไฟล์ต่างกั?r\nชื่อไฟล์:%1\r\nขนาดไฟล์เซิฟเวอร?%2, ขนาดไฟล์ที่ดาวโหลด:%3, server fileCRC:%4, file CRC ที?download :%5|"			
			"|EXE_HTTPManager::UpdateOneFile_6|ขนาดไฟล์ที?download ถูกเปลี่ยนแปลงแล้ว\r\nไฟล์?อมูล patch ยังไม่ถู?renew หรือว่?r\nอาจเป็นไปได้ที่ติดไวรั?r\nหากปัญหาเกิดขึ้นต่อเนื่อ?กรุณาทำตามวิธีด้านล่าง\r\n\r\n1.remove folder [lostsaga]\r\n   Tool ขอ?IE 7 -> Internet option->General->Delete->All Delete->[ที่หัว??Form data ,saved information that you have type into forms] ติ๊กถู?>yes\r\n    Tool ขอ?IE 6->Internet option->General->ลบ cookies ->ตกลง\r\n                                   Tool ->Internet option->General->ลบ file ->[ลบรายการ offline ทั้งหม? ติ๊กถู?>|"			
			"|EXE_HTTPManager::UpdateOneFile_7|ขนาดไฟล์เซิฟเวอร?%1, ขนาดไฟล์ที่ดาวโหลด:%2, server fileCRC:%3|"			
			"|EXE_HTTPManager::UpdateOneFile_8|เกิด error ในการรวมไฟล์\r\nเริ่มการทดลองใหม่อัตโนมัติ(รว?00ครั้?\r\nหากต้องการปิดโปรแกรม\r\nกรุณาคลิกที่ปุ่ม X ของการอัพเดทอัตโนมัต?r\n(Error Num:219)\r\n\r\n|"			
			"|EXE_HTTPManager::UpdateOneFile_9|ขนาดไฟล์เซิฟเวอร?%1, ขนาดไฟล์ที่ดาวโหลด:%2, server fileCRC:%3|"			
			"|EXE_HTTPManager::UpdateOneFile_10|เกิด error ในการคลา?zip file \r\nเริ่มการทดลองใหม่อัตโนมัติ(รว?00ครั้?\r\nหากต้องการปิดโปรแกรม\r\nกรุณาคลิกที่ปุ่ม X ของการอัพเดทอัตโนมัต?r\n(Error Num:220)\r\n\r\n|"			
			"|EXE_HTTPManager::UpdateOneFile_11|ขนาดไฟล์เซิฟเวอร?%1, ขนาดไฟล์ที่ดาวโหลด:%2, server fileCRC:%3|"			
			"|EXE_HTTPManager::UpdateOneFile_12|เกิด error ในขณ?copy file\r\nเริ่มการทดลองใหม่อัตโนมัติ(รว?00ครั้?\r\nหากต้องการปิดโปรแกรม\r\nกรุณาคลิกที่ปุ่ม X ของการอัพเดทอัตโนมัต?r\n(Error Num:221)\r\n\r\n|"			
			"|EXE_HTTPManager::UpdateOneFile_13|ขนาดไฟล์เซิฟเวอร?%1, ขนาดไฟล์ที่ดาวโหลด:%2|"			
			"|EXE_HTTPManager::UpdateOneFile_14|install full version ล้มเหลวแล้?r\nเริ่มการทดลองใหม่อัตโนมัติ(รว?00ครั้?\r\nหากต้องการปิดโปรแกรม\r\nกรุณาคลิกที่ปุ่ม X ของการอัพเดทอัตโนมัต?r\n(Error Num:217)\r\n\r\n|"			
			"|EXE_ioErrorDlg::ShowErrorDlg_1|Ver : %1\r\n--- system specification ---\r\n%2\r\n\r\n--- ?อมูล error ---\r\n%3|"
   		    "|EXE_ioLoginDlg::FirstConnectServer_1|กำลังเชื่อมต่อ Server Network %1|"
			"|EXE_ioLoginDlg::OnTimer_1|ไม่มีการตอบรับจา?Server %1 กำลังเชื่อมต่อ Server Network %2|"
			"|EXE_ioLoginDlg::OnTimer_2|ไม่มีการตอบรับจา?Server %1 สิ้นสุดการพยายามในการเชื่อมต่อ, กำลังเชื่อมต่อ Server Network %2|"
			"|EXE_ioLoginDlg::SendServer_1|ส่?Message ขอ Login ไปยั?Server %1 แล้ว, รอการตอบรับจาก Login Server|"
			"|EXE_ioLoginDlg::SetTextNetworkConnected_1|เชื่อมต่?Server Network %1 สำเร็จ|";
			*/
}

}